apiVersion: v1
kind: Secret
metadata:
  name: ceph-admin
  namespace: kube-system
type: Opaque
stringData:
  adminID: ENC[AES256_GCM,data:ETA4pRY=,iv:fjYm/Ov6J1SabcvpET1RnA8BZ/Hxgpb5G+X5DSWPg8w=,tag:bjKMgpB/Q3lPf+OY2/uwBQ==,type:str]
  adminKey: ENC[AES256_GCM,data:Fz91jEUnuwJf2skx3Sax6Jw+ms+HJkt6H61X6dHDmrvGPnOKRADxMw==,iv:hPeG3JZ2VE/uoTW2Sue1rnN0rcatM6X4K2u6ATncHhc=,tag:HJgvNcVvrDbsWUfB0wI4ZA==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcDZYaEFhTUo0YVIrVDZw
        T3JiNmMxMVd4NEgrQTZlRy9ldVliWU5tQkM4CmRqWXQ1Tis1NUFGM1FGMUtReVFC
        bHVyZmlYeDd6RG5UeWl0MUdpMzQ4QkUKLS0tIDlQRExQRlpPeXozc0w4d0VhSUdM
        ZkxmdXpCUXlkUW1GbGFlY2V6YU4vTE0KphYqtWB4KGFgisduxwqWYHOH5BRu5sr1
        E6y0Nx3LAgN//YosJtZHrmIOsconhNPjS2D1JDuecdff3sf4Nfoj9w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-13T19:57:15Z"
  mac: ENC[AES256_GCM,data:e4dySiiwVaUtLM3Iawi6ytQ8ilfgoUnkaKIUFVLgHyYzBvr70psJ0Ye98l3zJNvMaVSeuIlb1VvimK1I0dSWweE/068tzRvcNR1zcbFRM3U6/UN5taPRGathPt9bYtbnryafo72KcVHCDKDYCeVgVV0p2TZtxOhLJFTPuHj9xOE=,iv:6YjKeuL0T5WUVJp+iF4YWHWNG3H8RuCuhcA4AO5MTbs=,tag:KiK1j8LHNytHpOXk9jT+qw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
