apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argo
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
  hostnames:
    - argo.krapulax.dev
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaVZmWXlnUUtoWVdVOUxB
        UWhVQWNUQldOUURCZ0hMYWZkU2dhNmZTZVdnCmY0bmhnQ3FRT3hRV1NORmNVTlRR
        cXNwZU1MNVFCS05vbkV2bjdQWGpuSm8KLS0tIFF1L2pXVEFNdU1vSnZ0bmdXZ0sr
        T0RLZTYrRHJWMGppYUVka25aTXM4NTgKRHJLd4hqh7xEFF6YbSg3ydijG8qIsESc
        DW29IMB/K2hLz4YAbS1wRxhqa3S4YN6npt7M2E/d4zhplN+rfW7r4g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T19:35:52Z"
  mac: ENC[AES256_GCM,data:WnkjF878EW0YsXhOkYWUxQNDkP2Y9BZWTHncBGqm43hasXnEVRN5eQm72Q59kK0YUXg2+wiVLq7Q+1fm94SgoZ14HshaoJBsrwc2KdBDR82asMjk01hZehJLSRd1BtWnVQkTH8gftWdHTJQW5n2b3fD4QA8GUXwHh9w5N75IeZ4=,iv:9gOjoCpzZkwHtJ08o+uLImQZY8exA3hBdxB7Y2IsQl0=,tag:jwntJeuZiMl3BGU1wSMBFA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
