apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argo
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
  hostnames:
    - argo.krapulax.dev
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeUhQdDRzQmc5NHd4NGsz
        VTdXU1dnalRxSU9LRk5KNU5TMlQwWGVGbENBCmplb2QzemcvaGNXM21vNzVtZWFq
        ZWppVTAvQ0wwbXpYM3lPY09SMWZuZ2sKLS0tIGRDY1RYTnE4bksxTHJwaDZnYkQw
        anVOSEFsUmlEOEZxN0k4dCt3em9TdzAK5fuUGkR1QbqTGAJ2tuyDGJdceRpXWcZP
        d9St+BwgsfVwlBqBqI8YNFP22FNHVq+0xcnKOUUx8OITVXdRhZlaCQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T20:03:32Z"
  mac: ENC[AES256_GCM,data:MDFC/B1Un+o+UqSA90ux6bhAn2H/glIQ3D0c8ptcK1sQLhJeVX3UnwRfxZSPVMWxYxoKkkBYGQ5RYcD8Z6wh8DCWUcZIL2PE39HepOAX2/a6rFzFMZ1yivpzHKE9IalI3tKk625Ipw5j3/3CQOLjO6vTjPcuCE0/XKPfdJMCX6w=,iv:eswh/QGA5/AHm+lr5/6xgQkJy6RqUZAaODCusLTi9Lg=,tag:lHu5pwheQp5KyRXb4vw0WQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
