apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argo
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
  hostnames:
    - argo.krapulax.dev
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQN3hlMm14VHh5ZG90YkdL
        dmJKblQ1elhXYlBXNXlKK3NVV3MzMkRFZzJFCnNKOXJzME9scTJPZmxlY3J3YWZZ
        VW1ZWWowVVFQWGkvMEZqdDFvNDJiMFkKLS0tIGVZbzByeTFBVHdvNlpWRFVVK21V
        dUFpZnlsSTlZcUlhRkZxUnV6YzM0Vm8Kau8XD8gPINKieRQ526EumWO01FVGiieP
        CJtMdH0kNSkuYaTAhZ3GrRamtln6hxPMTJ7/NXh5hBlqGXx4Q0PhMw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T14:50:08Z"
  mac: ENC[AES256_GCM,data:VWUJ6WC0Mo75YY1TJ8gDNhZW8gECaAiBRbqKgb95nwkABBfWQY7CQua/iCfQ8JlpWUejhBuZNs9DSvEe2udDWtpM2j2TeFP181od1+k6elMvK9EGYfmrTDEKGGJVsnZDgN1w5U7Um0B+m1YYln8zIaJbjBeRMqFaU88tS2KcXdE=,iv:TXa869U1T8DbI/tXDVXdWtQSZC9uA9/miu3pCSOs5dA=,tag:f3jq4WTGBQdTOc/L1SYUpw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
