apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network
  hostnames:
    - grafana.krapulax.dev
  rules:
    - backendRefs:
        - name: kube-prometheus-stack-grafana
          port: 80
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHM2RGSzZHc0RHVzAyUVNE
        VWI0RGFWblZHN3NDeUViMmE5MUtTdjY2NEFzCktSdmJiR0dmdjY4cDNQMStVNk5U
        bHVGbDJIN3Z4WVUrTk4vYmwyWVhWSUkKLS0tIHV1dmkwQWVrU3h3Y0Q3b2hKQWNH
        S2hxUlRyUDBwV3dEdkM0RXV6WkdMdVEKfv5Ld6FEOyeMHQQDCoKsay81WNqSx74x
        5AQiK6nvdLXso7yY2UQRPwcHvTRzZP6iY4h+ZdmbLB2TsXXZu3TJFQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T20:06:36Z"
  mac: ENC[AES256_GCM,data:VqqK/9ZG1KKkqZh+z1byIashtXh6xo3yr3wJTo4acAp8VWUcGkXPi1OQkthNanDzLirvFnWhE0cH2stPwCzrrqRUvQsEo5ZD0pshqeKKLT/tB721eVpWrEAATLOeX96yzmpcykUKF2rzu6DGx+d/TTAa7stDWGJtiP3tIzhLipg=,iv:Lt4GT7ywTeMy/oZhMpvuB6HiuOb5MMVJhzPRsAy5sKo=,tag:TD949YWdZynzBtK2Qo3eLg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
