apiVersion: v1
kind: Secret
metadata:
  name: ceph-admin
  namespace: kube-system
type: Opaque
stringData:
  userID: ENC[AES256_GCM,data:DV/QPYI=,iv:HROqE57Cp6Y2efT6q6HKQnNJEBjVv2KoyNuR+P7wsVQ=,tag:EyRXMxrV/ARmpPyj0qKQ9g==,type:str]
  userKey: ENC[AES256_GCM,data:BdguEyKmBNkEJiJbEJtZlLtahsKv+YJVL3vjvqVJnmXTGbHYnIHFeA==,iv:beksYOfM/jkO43jxjl2tF7uJ6V6UUVVEP3ZM8li37Ws=,tag:yuvqFBLmOiVC0ziBmA3Pow==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdVR3Vkc0K21PRlVtSnlJ
        Qk05VlhPQXA0UmpYR1BTVUsvRWtmQ2t6R2w0CkJCZ1lRM3hnNFFRTEt6Nk1hN2pv
        clo1NEYwV1A0U0JiZ3NNcjd1THcrSncKLS0tIGRHdWwyREVoc09neWh5cERobXJx
        UWh3aW12cTkrdElLTGxSNkNtQ1BHWVUKuVuFvi062DO6kvw/7IiHfPYW4kTO2UUs
        2hy3o+icYuSqMg30qpw9wqygq6H8iM+WWgsF/x6eH1Ne+YgwkGqM3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-13T19:57:08Z"
  mac: ENC[AES256_GCM,data:bVpCTCe150cL5Ik5j7d8V3FA5ZhrwjIvO8T96VfRo83+lbSQKqAs+mVL+wx93Qc8W6S2OIBhE74LhqqW94iYcCSzUajnaRFwmHZrTrTuFi7K8ftMja6IeOIshqmg9w9PMi46rB2yI83yd56OaEMv+jHDjZUAN0CVPJv8o6wrvxU=,iv:La0HIqX6osD7ny9SGmiljrC7xyOEU7wJhOG5y84bQ7M=,tag:Y2fi8nTkHABql88amic8Dw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
