apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: krapulax-dev-production
spec:
  dnsNames:
    - krapulax.dev
    - '*.krapulax.dev'
  duration: 160h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
  secretName: krapulax-dev-production-tls
  usages:
    - digital signature
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bitIaVhlbHFYblhoN00z
        ZFRMb0NkaDlybFUzRWhzSkdFZkN3U3RKVjNBCnZLMlZFVTFsUXV5YWgvSUh3QlBG
        WHZQNDVzbm5KWmtvVHF6QTVjUndoWW8KLS0tIFFkTWU2d3VlZjcwWVBhUHo0SVJi
        dTVHc1ZKMk5OMUdNYVlvSDBNam5UL1kKmiLlQLPXIPMXyc/mYlvCk/C7I3Caq12G
        6Z/udldP86uUdktH4NPItRZg0fJ8qo5S8+H+8Yl2vYjAHhpH9U62Og==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-13T22:54:34Z"
  mac: ENC[AES256_GCM,data:0hfUc4osfs71E1iKIduFO1BwB1XJLFkJ75FY94aICVK4vEq2wJZhKbcD/PLIXBzdVHbpYYAyRSV9YndQbDeSQ6fuFqHQg2HgbIbzFZ1UT3fGaRvfOVxIrHt4OEajbTBmLEY84dx9KUuyZTIHC9/cAcO94IP82J4+r9FfC65XA74=,iv:ybzeK6cacTp73i23M5Aq7TIR4mYlSbZXVXwTY2+XH/s=,tag:fzYx3eWCbSYN/e0XZTsleA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
