apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: krapulax-dev-production
spec:
  dnsNames:
    - krapulax.dev
    - '*.krapulax.dev'
  duration: 160h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
  secretName: krapulax-dev-production-tls
  usages:
    - digital signature
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiaEt6VWZkM2U5blJvdWI4
        NGZ6TVNuV3RveWhyaVUxWWpvQTZMd1pxMXcwCmpjZUNZOWxJQU1MRjl0ZWNhcVB5
        akcvYm42OWhnZzFFZC9uYnJhdVNXOG8KLS0tIGVPNEhPWVhNVExpeGFySG1OeDQ0
        b05rN0xUZkRTZ2pFcWN3K014Q1FNSVEK3uxHqQ+WGHZNpDTHHQ7WjP8yatCZILs4
        2qorolecI7GAcrCypkolU3Bgj8OIVxtxugftqfWB18CiRieuurvtzg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T17:15:39Z"
  mac: ENC[AES256_GCM,data:DtyG98uyJ5sDMWkJ5a3g4A2ywPwISuExDz1BSviZdPQ+ebJpLm7aTSwoXToiJ+yAhu8+LQUp+xa/8WWy6rcXLbkfnCBLK1e/YmGvcfkm6SMqLZXvgYR4odk6sPmFsAGPvtxUR5QYwgz9ifInVccMYkbvRR5xoWkUHBkbEXEAzDY=,iv:3AOOVz/r3cF6C+pQDLYCpRR/u6SX16SFGdUjvTOehUk=,tag:4o6qhdGVmqYIl32AG8LtMA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
