apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy
spec:
  logging:
    level:
      default: info
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
        container:
          imageRepository: mirror.gcr.io/envoyproxy/envoy
          resources:
            requests:
              cpu: 100m
            limits:
              memory: 1Gi
      envoyService:
        externalTrafficPolicy: Cluster
  shutdown:
    drainTimeout: 180s
  telemetry:
    metrics:
      prometheus:
        compression:
          type: Zstd
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNHdtSHRvc0w5TVVvNzRk
        VjQ3cTk5VGltdHp2V3h1a3FSMml1R0lNaUZzCnhKa1d3WXVzV3FDeWJyUGJNZ0pB
        ZEloU2hXbHJIZk1uSTZwWWxUL09HZncKLS0tIGh4d01SSm14VnliTHNYZE1qWU5U
        M2VkOVJ4cUF5ZnpLazM5OHd1MEd6SFkKDMhlXbFDJ24Nkq9n9M6912zzW+7ZvA+k
        uCf/vQwI3wrGOtRT+fZOmaxpsfk0hLeVg0VrwmVQm1R+7qL4o1eKRg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T14:25:27Z"
  mac: ENC[AES256_GCM,data:L+g6Z8sGBEgYliVdW6n33MFA6zujS+4k/fJwN5+Y249BkEtdhvMUwNBA/AegPhRn23N0oBCA9L6RZY5WD+jmA/rL9AkIdc0n/wjqEqXaXvmynWl9aar4TEmw27wrW2/v/H9m7oIWcap1B6wVLx+Xfk89ffVlFRvqPPeKHDIk5/E=,iv:BlnCuM47JwuSA8eDVWwW8uZ28/uttfbBPV+sa7pcJKo=,tag:can39Ywi7fwKEL7wzrqDAw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: envoy
    namespace: network
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNHdtSHRvc0w5TVVvNzRk
        VjQ3cTk5VGltdHp2V3h1a3FSMml1R0lNaUZzCnhKa1d3WXVzV3FDeWJyUGJNZ0pB
        ZEloU2hXbHJIZk1uSTZwWWxUL09HZncKLS0tIGh4d01SSm14VnliTHNYZE1qWU5U
        M2VkOVJ4cUF5ZnpLazM5OHd1MEd6SFkKDMhlXbFDJ24Nkq9n9M6912zzW+7ZvA+k
        uCf/vQwI3wrGOtRT+fZOmaxpsfk0hLeVg0VrwmVQm1R+7qL4o1eKRg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T14:25:27Z"
  mac: ENC[AES256_GCM,data:L+g6Z8sGBEgYliVdW6n33MFA6zujS+4k/fJwN5+Y249BkEtdhvMUwNBA/AegPhRn23N0oBCA9L6RZY5WD+jmA/rL9AkIdc0n/wjqEqXaXvmynWl9aar4TEmw27wrW2/v/H9m7oIWcap1B6wVLx+Xfk89ffVlFRvqPPeKHDIk5/E=,iv:BlnCuM47JwuSA8eDVWwW8uZ28/uttfbBPV+sa7pcJKo=,tag:can39Ywi7fwKEL7wzrqDAw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-external
  annotations:
    external-dns.alpha.kubernetes.io/target: external.krapulax.dev
spec:
  gatewayClassName: envoy
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: external.krapulax.dev
      lbipam.cilium.io/ips: 10.0.40.103
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: krapulax-dev-production-tls
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNHdtSHRvc0w5TVVvNzRk
        VjQ3cTk5VGltdHp2V3h1a3FSMml1R0lNaUZzCnhKa1d3WXVzV3FDeWJyUGJNZ0pB
        ZEloU2hXbHJIZk1uSTZwWWxUL09HZncKLS0tIGh4d01SSm14VnliTHNYZE1qWU5U
        M2VkOVJ4cUF5ZnpLazM5OHd1MEd6SFkKDMhlXbFDJ24Nkq9n9M6912zzW+7ZvA+k
        uCf/vQwI3wrGOtRT+fZOmaxpsfk0hLeVg0VrwmVQm1R+7qL4o1eKRg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T14:25:27Z"
  mac: ENC[AES256_GCM,data:L+g6Z8sGBEgYliVdW6n33MFA6zujS+4k/fJwN5+Y249BkEtdhvMUwNBA/AegPhRn23N0oBCA9L6RZY5WD+jmA/rL9AkIdc0n/wjqEqXaXvmynWl9aar4TEmw27wrW2/v/H9m7oIWcap1B6wVLx+Xfk89ffVlFRvqPPeKHDIk5/E=,iv:BlnCuM47JwuSA8eDVWwW8uZ28/uttfbBPV+sa7pcJKo=,tag:can39Ywi7fwKEL7wzrqDAw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-internal
  annotations:
    external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
spec:
  gatewayClassName: envoy
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: internal.krapulax.dev
      lbipam.cilium.io/ips: 10.0.40.102
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: krapulax-dev-production-tls
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNHdtSHRvc0w5TVVvNzRk
        VjQ3cTk5VGltdHp2V3h1a3FSMml1R0lNaUZzCnhKa1d3WXVzV3FDeWJyUGJNZ0pB
        ZEloU2hXbHJIZk1uSTZwWWxUL09HZncKLS0tIGh4d01SSm14VnliTHNYZE1qWU5U
        M2VkOVJ4cUF5ZnpLazM5OHd1MEd6SFkKDMhlXbFDJ24Nkq9n9M6912zzW+7ZvA+k
        uCf/vQwI3wrGOtRT+fZOmaxpsfk0hLeVg0VrwmVQm1R+7qL4o1eKRg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T14:25:27Z"
  mac: ENC[AES256_GCM,data:L+g6Z8sGBEgYliVdW6n33MFA6zujS+4k/fJwN5+Y249BkEtdhvMUwNBA/AegPhRn23N0oBCA9L6RZY5WD+jmA/rL9AkIdc0n/wjqEqXaXvmynWl9aar4TEmw27wrW2/v/H9m7oIWcap1B6wVLx+Xfk89ffVlFRvqPPeKHDIk5/E=,iv:BlnCuM47JwuSA8eDVWwW8uZ28/uttfbBPV+sa7pcJKo=,tag:can39Ywi7fwKEL7wzrqDAw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: envoy
spec:
  compressor:
    - type: Zstd
      zstd: {}
    - type: Brotli
      brotli: {}
    - type: Gzip
      gzip: {}
  retry:
    numRetries: 2
    retryOn:
      triggers:
        - reset
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: Gateway
  tcpKeepalive: {}
  timeout:
    http:
      requestTimeout: 0s
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNHdtSHRvc0w5TVVvNzRk
        VjQ3cTk5VGltdHp2V3h1a3FSMml1R0lNaUZzCnhKa1d3WXVzV3FDeWJyUGJNZ0pB
        ZEloU2hXbHJIZk1uSTZwWWxUL09HZncKLS0tIGh4d01SSm14VnliTHNYZE1qWU5U
        M2VkOVJ4cUF5ZnpLazM5OHd1MEd6SFkKDMhlXbFDJ24Nkq9n9M6912zzW+7ZvA+k
        uCf/vQwI3wrGOtRT+fZOmaxpsfk0hLeVg0VrwmVQm1R+7qL4o1eKRg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T14:25:27Z"
  mac: ENC[AES256_GCM,data:L+g6Z8sGBEgYliVdW6n33MFA6zujS+4k/fJwN5+Y249BkEtdhvMUwNBA/AegPhRn23N0oBCA9L6RZY5WD+jmA/rL9AkIdc0n/wjqEqXaXvmynWl9aar4TEmw27wrW2/v/H9m7oIWcap1B6wVLx+Xfk89ffVlFRvqPPeKHDIk5/E=,iv:BlnCuM47JwuSA8eDVWwW8uZ28/uttfbBPV+sa7pcJKo=,tag:can39Ywi7fwKEL7wzrqDAw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: envoy
spec:
  clientIPDetection:
    xForwardedFor:
      trustedCIDRs:
        - 10.42.0.0/16
  http2:
    onInvalidMessage: TerminateStream
  http3: {}
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: Gateway
  tcpKeepalive: {}
  tls:
    minVersion: "1.2"
    alpnProtocols:
      - h2
      - http/1.1
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNHdtSHRvc0w5TVVvNzRk
        VjQ3cTk5VGltdHp2V3h1a3FSMml1R0lNaUZzCnhKa1d3WXVzV3FDeWJyUGJNZ0pB
        ZEloU2hXbHJIZk1uSTZwWWxUL09HZncKLS0tIGh4d01SSm14VnliTHNYZE1qWU5U
        M2VkOVJ4cUF5ZnpLazM5OHd1MEd6SFkKDMhlXbFDJ24Nkq9n9M6912zzW+7ZvA+k
        uCf/vQwI3wrGOtRT+fZOmaxpsfk0hLeVg0VrwmVQm1R+7qL4o1eKRg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T14:25:27Z"
  mac: ENC[AES256_GCM,data:L+g6Z8sGBEgYliVdW6n33MFA6zujS+4k/fJwN5+Y249BkEtdhvMUwNBA/AegPhRn23N0oBCA9L6RZY5WD+jmA/rL9AkIdc0n/wjqEqXaXvmynWl9aar4TEmw27wrW2/v/H9m7oIWcap1B6wVLx+Xfk89ffVlFRvqPPeKHDIk5/E=,iv:BlnCuM47JwuSA8eDVWwW8uZ28/uttfbBPV+sa7pcJKo=,tag:can39Ywi7fwKEL7wzrqDAw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-redirect
  annotations:
    external-dns.alpha.kubernetes.io/controller: none
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
      sectionName: http
    - name: envoy-internal
      namespace: network
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNHdtSHRvc0w5TVVvNzRk
        VjQ3cTk5VGltdHp2V3h1a3FSMml1R0lNaUZzCnhKa1d3WXVzV3FDeWJyUGJNZ0pB
        ZEloU2hXbHJIZk1uSTZwWWxUL09HZncKLS0tIGh4d01SSm14VnliTHNYZE1qWU5U
        M2VkOVJ4cUF5ZnpLazM5OHd1MEd6SFkKDMhlXbFDJ24Nkq9n9M6912zzW+7ZvA+k
        uCf/vQwI3wrGOtRT+fZOmaxpsfk0hLeVg0VrwmVQm1R+7qL4o1eKRg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T14:25:27Z"
  mac: ENC[AES256_GCM,data:L+g6Z8sGBEgYliVdW6n33MFA6zujS+4k/fJwN5+Y249BkEtdhvMUwNBA/AegPhRn23N0oBCA9L6RZY5WD+jmA/rL9AkIdc0n/wjqEqXaXvmynWl9aar4TEmw27wrW2/v/H9m7oIWcap1B6wVLx+Xfk89ffVlFRvqPPeKHDIk5/E=,iv:BlnCuM47JwuSA8eDVWwW8uZ28/uttfbBPV+sa7pcJKo=,tag:can39Ywi7fwKEL7wzrqDAw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
