apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy
spec:
  logging:
    level:
      default: info
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
        container:
          imageRepository: mirror.gcr.io/envoyproxy/envoy
          resources:
            requests:
              cpu: 100m
            limits:
              memory: 1Gi
      envoyService:
        externalTrafficPolicy: Cluster
  shutdown:
    drainTimeout: 180s
  telemetry:
    metrics:
      prometheus:
        compression:
          type: Zstd
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOTYvSDZIUWNweStHUUUw
        dFFlUVgwMjk0d1RTaTNwRmh2NjFNSGlOVndnCmdpM2YzeDNuaU1XZEZWV1RLWXE5
        TnRlcWdUWE9JeDkzRkZjRnBLVFozRG8KLS0tIHQvc0NoVVVIdWVXRlMrVG8rZ1I5
        VExpYjZtM05WajZkZnZGZVZIL1JuRGMK5mdTgqccECyC0Q4I4g/2BzDZy+Oj3NWv
        8V2dm0Hnpp/X4I7IUn83BHZs79T3f0JYA6dUyv8Jrz6lSgdiibyVkA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T15:22:02Z"
  mac: ENC[AES256_GCM,data:a9Uz/ZqZfy6jbBgCkMKneosX3K9w6rxGxjIhBUZBkCdj/ZTwRer6hPfZIC27T1RQGdIDm3OBwmCHxgLbSWyaUn+eVccbp0qkJyTb4+PO7M0NXTMpSIdRQEQepMV25dTB5XV9MBLnk6C43ynPT7c6we0rr/wAhcOvpTq0WERjPfs=,iv:TmPBMQMPEt6xnEjtZYrB8iflwhXGM0TF2WdPwGvYdrw=,tag:E1qtAKfq1sV1A2j5vw7YcA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: envoy
    namespace: network
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOTYvSDZIUWNweStHUUUw
        dFFlUVgwMjk0d1RTaTNwRmh2NjFNSGlOVndnCmdpM2YzeDNuaU1XZEZWV1RLWXE5
        TnRlcWdUWE9JeDkzRkZjRnBLVFozRG8KLS0tIHQvc0NoVVVIdWVXRlMrVG8rZ1I5
        VExpYjZtM05WajZkZnZGZVZIL1JuRGMK5mdTgqccECyC0Q4I4g/2BzDZy+Oj3NWv
        8V2dm0Hnpp/X4I7IUn83BHZs79T3f0JYA6dUyv8Jrz6lSgdiibyVkA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T15:22:02Z"
  mac: ENC[AES256_GCM,data:a9Uz/ZqZfy6jbBgCkMKneosX3K9w6rxGxjIhBUZBkCdj/ZTwRer6hPfZIC27T1RQGdIDm3OBwmCHxgLbSWyaUn+eVccbp0qkJyTb4+PO7M0NXTMpSIdRQEQepMV25dTB5XV9MBLnk6C43ynPT7c6we0rr/wAhcOvpTq0WERjPfs=,iv:TmPBMQMPEt6xnEjtZYrB8iflwhXGM0TF2WdPwGvYdrw=,tag:E1qtAKfq1sV1A2j5vw7YcA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-external
  annotations:
    external-dns.alpha.kubernetes.io/target: external.krapulax.dev
spec:
  gatewayClassName: envoy
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: external.krapulax.dev
      lbipam.cilium.io/ips: 10.0.40.103
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: krapulax-dev-production-tls
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOTYvSDZIUWNweStHUUUw
        dFFlUVgwMjk0d1RTaTNwRmh2NjFNSGlOVndnCmdpM2YzeDNuaU1XZEZWV1RLWXE5
        TnRlcWdUWE9JeDkzRkZjRnBLVFozRG8KLS0tIHQvc0NoVVVIdWVXRlMrVG8rZ1I5
        VExpYjZtM05WajZkZnZGZVZIL1JuRGMK5mdTgqccECyC0Q4I4g/2BzDZy+Oj3NWv
        8V2dm0Hnpp/X4I7IUn83BHZs79T3f0JYA6dUyv8Jrz6lSgdiibyVkA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T15:22:02Z"
  mac: ENC[AES256_GCM,data:a9Uz/ZqZfy6jbBgCkMKneosX3K9w6rxGxjIhBUZBkCdj/ZTwRer6hPfZIC27T1RQGdIDm3OBwmCHxgLbSWyaUn+eVccbp0qkJyTb4+PO7M0NXTMpSIdRQEQepMV25dTB5XV9MBLnk6C43ynPT7c6we0rr/wAhcOvpTq0WERjPfs=,iv:TmPBMQMPEt6xnEjtZYrB8iflwhXGM0TF2WdPwGvYdrw=,tag:E1qtAKfq1sV1A2j5vw7YcA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-internal
  annotations:
    external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
spec:
  gatewayClassName: envoy
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: internal.krapulax.dev
      lbipam.cilium.io/ips: 10.0.40.102
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: krapulax-dev-production-tls
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOTYvSDZIUWNweStHUUUw
        dFFlUVgwMjk0d1RTaTNwRmh2NjFNSGlOVndnCmdpM2YzeDNuaU1XZEZWV1RLWXE5
        TnRlcWdUWE9JeDkzRkZjRnBLVFozRG8KLS0tIHQvc0NoVVVIdWVXRlMrVG8rZ1I5
        VExpYjZtM05WajZkZnZGZVZIL1JuRGMK5mdTgqccECyC0Q4I4g/2BzDZy+Oj3NWv
        8V2dm0Hnpp/X4I7IUn83BHZs79T3f0JYA6dUyv8Jrz6lSgdiibyVkA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T15:22:02Z"
  mac: ENC[AES256_GCM,data:a9Uz/ZqZfy6jbBgCkMKneosX3K9w6rxGxjIhBUZBkCdj/ZTwRer6hPfZIC27T1RQGdIDm3OBwmCHxgLbSWyaUn+eVccbp0qkJyTb4+PO7M0NXTMpSIdRQEQepMV25dTB5XV9MBLnk6C43ynPT7c6we0rr/wAhcOvpTq0WERjPfs=,iv:TmPBMQMPEt6xnEjtZYrB8iflwhXGM0TF2WdPwGvYdrw=,tag:E1qtAKfq1sV1A2j5vw7YcA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: envoy
spec:
  compressor:
    - type: Zstd
      zstd: {}
    - type: Brotli
      brotli: {}
    - type: Gzip
      gzip: {}
  retry:
    numRetries: 2
    retryOn:
      triggers:
        - reset
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: Gateway
  tcpKeepalive: {}
  timeout:
    http:
      requestTimeout: 0s
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOTYvSDZIUWNweStHUUUw
        dFFlUVgwMjk0d1RTaTNwRmh2NjFNSGlOVndnCmdpM2YzeDNuaU1XZEZWV1RLWXE5
        TnRlcWdUWE9JeDkzRkZjRnBLVFozRG8KLS0tIHQvc0NoVVVIdWVXRlMrVG8rZ1I5
        VExpYjZtM05WajZkZnZGZVZIL1JuRGMK5mdTgqccECyC0Q4I4g/2BzDZy+Oj3NWv
        8V2dm0Hnpp/X4I7IUn83BHZs79T3f0JYA6dUyv8Jrz6lSgdiibyVkA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T15:22:02Z"
  mac: ENC[AES256_GCM,data:a9Uz/ZqZfy6jbBgCkMKneosX3K9w6rxGxjIhBUZBkCdj/ZTwRer6hPfZIC27T1RQGdIDm3OBwmCHxgLbSWyaUn+eVccbp0qkJyTb4+PO7M0NXTMpSIdRQEQepMV25dTB5XV9MBLnk6C43ynPT7c6we0rr/wAhcOvpTq0WERjPfs=,iv:TmPBMQMPEt6xnEjtZYrB8iflwhXGM0TF2WdPwGvYdrw=,tag:E1qtAKfq1sV1A2j5vw7YcA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: envoy
spec:
  clientIPDetection:
    xForwardedFor:
      trustedCIDRs:
        - 10.42.0.0/16
  http2:
    onInvalidMessage: TerminateStream
  http3: {}
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: Gateway
  tcpKeepalive: {}
  tls:
    minVersion: "1.2"
    alpnProtocols:
      - h2
      - http/1.1
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOTYvSDZIUWNweStHUUUw
        dFFlUVgwMjk0d1RTaTNwRmh2NjFNSGlOVndnCmdpM2YzeDNuaU1XZEZWV1RLWXE5
        TnRlcWdUWE9JeDkzRkZjRnBLVFozRG8KLS0tIHQvc0NoVVVIdWVXRlMrVG8rZ1I5
        VExpYjZtM05WajZkZnZGZVZIL1JuRGMK5mdTgqccECyC0Q4I4g/2BzDZy+Oj3NWv
        8V2dm0Hnpp/X4I7IUn83BHZs79T3f0JYA6dUyv8Jrz6lSgdiibyVkA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T15:22:02Z"
  mac: ENC[AES256_GCM,data:a9Uz/ZqZfy6jbBgCkMKneosX3K9w6rxGxjIhBUZBkCdj/ZTwRer6hPfZIC27T1RQGdIDm3OBwmCHxgLbSWyaUn+eVccbp0qkJyTb4+PO7M0NXTMpSIdRQEQepMV25dTB5XV9MBLnk6C43ynPT7c6we0rr/wAhcOvpTq0WERjPfs=,iv:TmPBMQMPEt6xnEjtZYrB8iflwhXGM0TF2WdPwGvYdrw=,tag:E1qtAKfq1sV1A2j5vw7YcA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-redirect
  annotations:
    external-dns.alpha.kubernetes.io/controller: none
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
      sectionName: http
    - name: envoy-internal
      namespace: network
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOTYvSDZIUWNweStHUUUw
        dFFlUVgwMjk0d1RTaTNwRmh2NjFNSGlOVndnCmdpM2YzeDNuaU1XZEZWV1RLWXE5
        TnRlcWdUWE9JeDkzRkZjRnBLVFozRG8KLS0tIHQvc0NoVVVIdWVXRlMrVG8rZ1I5
        VExpYjZtM05WajZkZnZGZVZIL1JuRGMK5mdTgqccECyC0Q4I4g/2BzDZy+Oj3NWv
        8V2dm0Hnpp/X4I7IUn83BHZs79T3f0JYA6dUyv8Jrz6lSgdiibyVkA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T15:22:02Z"
  mac: ENC[AES256_GCM,data:a9Uz/ZqZfy6jbBgCkMKneosX3K9w6rxGxjIhBUZBkCdj/ZTwRer6hPfZIC27T1RQGdIDm3OBwmCHxgLbSWyaUn+eVccbp0qkJyTb4+PO7M0NXTMpSIdRQEQepMV25dTB5XV9MBLnk6C43ynPT7c6we0rr/wAhcOvpTq0WERjPfs=,iv:TmPBMQMPEt6xnEjtZYrB8iflwhXGM0TF2WdPwGvYdrw=,tag:E1qtAKfq1sV1A2j5vw7YcA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
