apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy
spec:
  logging:
    level:
      default: info
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
        container:
          imageRepository: mirror.gcr.io/envoyproxy/envoy
          resources:
            requests:
              cpu: 100m
            limits:
              memory: 1Gi
      envoyService:
        externalTrafficPolicy: Cluster
  shutdown:
    drainTimeout: 180s
  telemetry:
    metrics:
      prometheus:
        compression:
          type: Zstd
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQjhFYVU4dXM1b1U1Q21U
        enJqSVlwcmpUOFYvek1lUFd0d1BVUzhWR0hJCkxNWXR1NGlxTHFaSnNJSks5eU5a
        b1ljODNxTzgzY2R3aC8wNVdEVkIwQlkKLS0tIExDckM0OVo0U1hHemZvd0pXLzJn
        dEhiTlRpQUQzRlNRakttNENGV3F2bWcKoAYVPlI2Zx5jyss6PC+0MkSyl6CpGX78
        t7hoKpaEWTTaNhgohxUmkzybOQsDc3vgqdaGJtZzb0jcwTS+5MxyRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T11:22:49Z"
  mac: ENC[AES256_GCM,data:MCCuFGSobIwoaup3rO2AFDUI27fTg9KjMRYrNpwntjjE7EkXxIIAKfMTO1b+qg45oI6O7sdtZ+Lo0JTdHT47yJ3WgkCQlGN3xbEHi1HraVGWYCGENJvG8x4O/0YSgvFzEiPoRsp3PVRJZqltOkZEo4HXRZO4g1TpMqYfGADTvCs=,iv:9LlfKnY1cFh4isEbgnt0vqoKWyL7laE7ZIs/jjTLrAg=,tag:zF/W2T5mGY4PEiUic+twOQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: envoy
    namespace: network
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQjhFYVU4dXM1b1U1Q21U
        enJqSVlwcmpUOFYvek1lUFd0d1BVUzhWR0hJCkxNWXR1NGlxTHFaSnNJSks5eU5a
        b1ljODNxTzgzY2R3aC8wNVdEVkIwQlkKLS0tIExDckM0OVo0U1hHemZvd0pXLzJn
        dEhiTlRpQUQzRlNRakttNENGV3F2bWcKoAYVPlI2Zx5jyss6PC+0MkSyl6CpGX78
        t7hoKpaEWTTaNhgohxUmkzybOQsDc3vgqdaGJtZzb0jcwTS+5MxyRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T11:22:49Z"
  mac: ENC[AES256_GCM,data:MCCuFGSobIwoaup3rO2AFDUI27fTg9KjMRYrNpwntjjE7EkXxIIAKfMTO1b+qg45oI6O7sdtZ+Lo0JTdHT47yJ3WgkCQlGN3xbEHi1HraVGWYCGENJvG8x4O/0YSgvFzEiPoRsp3PVRJZqltOkZEo4HXRZO4g1TpMqYfGADTvCs=,iv:9LlfKnY1cFh4isEbgnt0vqoKWyL7laE7ZIs/jjTLrAg=,tag:zF/W2T5mGY4PEiUic+twOQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-external
  annotations:
    external-dns.alpha.kubernetes.io/target: external.k8s.krapulax.dev
spec:
  gatewayClassName: envoy
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: external.k8s.krapulax.dev
      lbipam.cilium.io/ips: 10.0.40.103
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: k8s-krapulax-dev-production-tls
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQjhFYVU4dXM1b1U1Q21U
        enJqSVlwcmpUOFYvek1lUFd0d1BVUzhWR0hJCkxNWXR1NGlxTHFaSnNJSks5eU5a
        b1ljODNxTzgzY2R3aC8wNVdEVkIwQlkKLS0tIExDckM0OVo0U1hHemZvd0pXLzJn
        dEhiTlRpQUQzRlNRakttNENGV3F2bWcKoAYVPlI2Zx5jyss6PC+0MkSyl6CpGX78
        t7hoKpaEWTTaNhgohxUmkzybOQsDc3vgqdaGJtZzb0jcwTS+5MxyRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T11:22:49Z"
  mac: ENC[AES256_GCM,data:MCCuFGSobIwoaup3rO2AFDUI27fTg9KjMRYrNpwntjjE7EkXxIIAKfMTO1b+qg45oI6O7sdtZ+Lo0JTdHT47yJ3WgkCQlGN3xbEHi1HraVGWYCGENJvG8x4O/0YSgvFzEiPoRsp3PVRJZqltOkZEo4HXRZO4g1TpMqYfGADTvCs=,iv:9LlfKnY1cFh4isEbgnt0vqoKWyL7laE7ZIs/jjTLrAg=,tag:zF/W2T5mGY4PEiUic+twOQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-internal
  annotations:
    external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
spec:
  gatewayClassName: envoy
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: internal.k8s.krapulax.dev
      lbipam.cilium.io/ips: 10.0.40.102
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: k8s-krapulax-dev-production-tls
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQjhFYVU4dXM1b1U1Q21U
        enJqSVlwcmpUOFYvek1lUFd0d1BVUzhWR0hJCkxNWXR1NGlxTHFaSnNJSks5eU5a
        b1ljODNxTzgzY2R3aC8wNVdEVkIwQlkKLS0tIExDckM0OVo0U1hHemZvd0pXLzJn
        dEhiTlRpQUQzRlNRakttNENGV3F2bWcKoAYVPlI2Zx5jyss6PC+0MkSyl6CpGX78
        t7hoKpaEWTTaNhgohxUmkzybOQsDc3vgqdaGJtZzb0jcwTS+5MxyRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T11:22:49Z"
  mac: ENC[AES256_GCM,data:MCCuFGSobIwoaup3rO2AFDUI27fTg9KjMRYrNpwntjjE7EkXxIIAKfMTO1b+qg45oI6O7sdtZ+Lo0JTdHT47yJ3WgkCQlGN3xbEHi1HraVGWYCGENJvG8x4O/0YSgvFzEiPoRsp3PVRJZqltOkZEo4HXRZO4g1TpMqYfGADTvCs=,iv:9LlfKnY1cFh4isEbgnt0vqoKWyL7laE7ZIs/jjTLrAg=,tag:zF/W2T5mGY4PEiUic+twOQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: envoy
spec:
  compressor:
    - type: Zstd
      zstd: {}
    - type: Brotli
      brotli: {}
    - type: Gzip
      gzip: {}
  retry:
    numRetries: 2
    retryOn:
      triggers:
        - reset
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: Gateway
  tcpKeepalive: {}
  timeout:
    http:
      requestTimeout: 0s
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQjhFYVU4dXM1b1U1Q21U
        enJqSVlwcmpUOFYvek1lUFd0d1BVUzhWR0hJCkxNWXR1NGlxTHFaSnNJSks5eU5a
        b1ljODNxTzgzY2R3aC8wNVdEVkIwQlkKLS0tIExDckM0OVo0U1hHemZvd0pXLzJn
        dEhiTlRpQUQzRlNRakttNENGV3F2bWcKoAYVPlI2Zx5jyss6PC+0MkSyl6CpGX78
        t7hoKpaEWTTaNhgohxUmkzybOQsDc3vgqdaGJtZzb0jcwTS+5MxyRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T11:22:49Z"
  mac: ENC[AES256_GCM,data:MCCuFGSobIwoaup3rO2AFDUI27fTg9KjMRYrNpwntjjE7EkXxIIAKfMTO1b+qg45oI6O7sdtZ+Lo0JTdHT47yJ3WgkCQlGN3xbEHi1HraVGWYCGENJvG8x4O/0YSgvFzEiPoRsp3PVRJZqltOkZEo4HXRZO4g1TpMqYfGADTvCs=,iv:9LlfKnY1cFh4isEbgnt0vqoKWyL7laE7ZIs/jjTLrAg=,tag:zF/W2T5mGY4PEiUic+twOQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: envoy
spec:
  clientIPDetection:
    xForwardedFor:
      trustedCIDRs:
        - 10.42.0.0/16
  http2:
    onInvalidMessage: TerminateStream
  http3: {}
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: Gateway
  tcpKeepalive: {}
  tls:
    minVersion: "1.2"
    alpnProtocols:
      - h2
      - http/1.1
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQjhFYVU4dXM1b1U1Q21U
        enJqSVlwcmpUOFYvek1lUFd0d1BVUzhWR0hJCkxNWXR1NGlxTHFaSnNJSks5eU5a
        b1ljODNxTzgzY2R3aC8wNVdEVkIwQlkKLS0tIExDckM0OVo0U1hHemZvd0pXLzJn
        dEhiTlRpQUQzRlNRakttNENGV3F2bWcKoAYVPlI2Zx5jyss6PC+0MkSyl6CpGX78
        t7hoKpaEWTTaNhgohxUmkzybOQsDc3vgqdaGJtZzb0jcwTS+5MxyRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T11:22:49Z"
  mac: ENC[AES256_GCM,data:MCCuFGSobIwoaup3rO2AFDUI27fTg9KjMRYrNpwntjjE7EkXxIIAKfMTO1b+qg45oI6O7sdtZ+Lo0JTdHT47yJ3WgkCQlGN3xbEHi1HraVGWYCGENJvG8x4O/0YSgvFzEiPoRsp3PVRJZqltOkZEo4HXRZO4g1TpMqYfGADTvCs=,iv:9LlfKnY1cFh4isEbgnt0vqoKWyL7laE7ZIs/jjTLrAg=,tag:zF/W2T5mGY4PEiUic+twOQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-redirect
  annotations:
    external-dns.alpha.kubernetes.io/controller: none
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
      sectionName: http
    - name: envoy-internal
      namespace: network
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQjhFYVU4dXM1b1U1Q21U
        enJqSVlwcmpUOFYvek1lUFd0d1BVUzhWR0hJCkxNWXR1NGlxTHFaSnNJSks5eU5a
        b1ljODNxTzgzY2R3aC8wNVdEVkIwQlkKLS0tIExDckM0OVo0U1hHemZvd0pXLzJn
        dEhiTlRpQUQzRlNRakttNENGV3F2bWcKoAYVPlI2Zx5jyss6PC+0MkSyl6CpGX78
        t7hoKpaEWTTaNhgohxUmkzybOQsDc3vgqdaGJtZzb0jcwTS+5MxyRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T11:22:49Z"
  mac: ENC[AES256_GCM,data:MCCuFGSobIwoaup3rO2AFDUI27fTg9KjMRYrNpwntjjE7EkXxIIAKfMTO1b+qg45oI6O7sdtZ+Lo0JTdHT47yJ3WgkCQlGN3xbEHi1HraVGWYCGENJvG8x4O/0YSgvFzEiPoRsp3PVRJZqltOkZEo4HXRZO4g1TpMqYfGADTvCs=,iv:9LlfKnY1cFh4isEbgnt0vqoKWyL7laE7ZIs/jjTLrAg=,tag:zF/W2T5mGY4PEiUic+twOQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
