route:
  app:
    hostnames:
      - echo.krapulax.dev
    parentRefs:
      - name: envoy-external
        namespace: network
        sectionName: https
    rules:
      - backendRefs:
          - identifier: app
            port: 8080
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1T0FwWVBUSmZ6TWlORFNB
        SkFOOEF5Y2hFV1VnaFkvRmxmd25YVEFhUkF3CjRZa3YrZURjUUVCMTFacktPN1pK
        SXJ2b01pT2xnd0RjWVduT1JscVN3b0kKLS0tIHUrV1UwbVBkdWR2bXRxT2NYcWlw
        Mm9tbG1ha1M1QmFveklsVm1NWmFvY3cK+bN42hxo0sIZOZpyBPlMUrRVyzdeJOXT
        n714wup4M8TY02bZY2nZfHlMGrQElfb7qaCp7SQpLjx9Z6wVL4SB3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T00:32:14Z"
  mac: ENC[AES256_GCM,data:zaiZJ3QGyVrmWNFix7Ff3dpel2JO7PSELoPzy5rIoNcyEKiozaYjZZDY7Cu1Ziex0W8Oymdpi/7AD1QMZYmHAOohls2OCNSeGRAw0DfBMMgEjlwDdyDu5EReqM6cfd1hgzw9FukFVcUg806Z76rkCvaShVkQWV8aEutzxIkLxhA=,iv:yz7IeYoDroYQBFIUv1C5YUjbMkD93gXbiXfrwnWuyOw=,tag:S8/tiQSo5H6l0dmzPqLX1Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
