fullnameOverride: cloudflare-dns
provider: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-dns-secret
        key: api-token
extraArgs:
  - --cloudflare-dns-records-per-page=1000
  - --cloudflare-proxied
  - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
  - --crd-source-kind=DNSEndpoint
  - --gateway-name=envoy-external
triggerLoopOnEvent: true
policy: sync
sources:
  - crd
  - gateway-httproute
txtPrefix: k8s.
txtOwnerId: default
domainFilters:
  - krapulax.dev
serviceMonitor:
  enabled: true
podAnnotations:
  secret.reloader.stakater.com/reload: cloudflare-dns-secret
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWU1rZEN4UnJqZG1QamlR
        czNEdXQyQUNTeU9rQXVXcTR6M1RVOUZnam4wCndmNTNCYVpjbjhyYVVYK0hla0xZ
        MmVtNURHU3h4U3V3STcxWnFhem5QWmcKLS0tIGpsTlQvWmlLdlp1QWZISDd2R2h3
        RUI0WCtDc1FWVmkyWk1mMk9RUkI0d0EKm9oNQEG9JEKM9znuQj7Wea+zAAJ7fFvt
        KLm1zgcfnrcLPbpZlv+AjChK+qKRbCDwyRoQjcMw2B2/r3PAMVa+ag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T10:42:13Z"
  mac: ENC[AES256_GCM,data:8LDBRe7NthWUbUwiJFS9AzAA+6HMaOiIHqjLmuRrfG1TvotRceJ7boXRVxZoe9vWpGic0r3ROXcqw4fbs4FU2UZ/S70c+lZ0GDOJHsqEwxtZfR0kb1wWbL8RRzHTvWEXln/9IVa6r2cbmgJkeMl+4DlsDTcSkD1TCwHftQHyCMY=,iv:beWI5GcmIuAFDHpV3THSGtW6NfiTsRlGbAVd0ZLAh0Y=,tag:rGtvTNDZZHb/sLjjjV/Xbw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
