fullnameOverride: cloudflare-dns
provider: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-dns-secret
        key: api-token
extraArgs:
  - --cloudflare-dns-records-per-page=1000
  - --cloudflare-proxied
  - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
  - --crd-source-kind=DNSEndpoint
  - --gateway-name=envoy-external
triggerLoopOnEvent: true
policy: sync
sources:
  - crd
  - gateway-httproute
txtPrefix: k8s.
txtOwnerId: default
domainFilters:
  - k8s.krapulax.dev
serviceMonitor:
  enabled: true
podAnnotations:
  secret.reloader.stakater.com/reload: cloudflare-dns-secret
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VzJDYVdSN0FuNzJtc2ov
        dHRtT3d2U1MySEQ1dmF2elhaV0w2MkllOWlBCkc4Q0JjVjFwem9Da0ZwYU5NMExo
        OTRSQXVMV2EvTWU4RlNEc3dRcFhHeUEKLS0tIHp4NG0yejRkdldZUjVlcGl3SERt
        QTQvWXBTdXd6ckF6OEsrSlNXNkVaZG8K6SbLZ8zxYmKwAZguMBeG1nqQjqFv8nrw
        s6jeA3WDUYYEhL4FsQEBaVPdYnAKpKHSZGbxiByteqbnswOtht/8kw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-11T19:15:56Z"
  mac: ENC[AES256_GCM,data:aBMzHEPfv5mJpWKy08d1VMZp09rL6Zrzht8x/lONIZAV/wkz3K1HfYH4p8A/ga8ViQpsYX4gzFM4EzA7tUcgtz2c3KBHWX0FQYwyx4RLSVfA4ylEB+vfGnW7t/R9M0mW8/xLtfk/3rSKI6EoiLSyCMqEyfTmDuhLunMNDk3+MOE=,iv:IgVchRlvsopEUSoZzm8aCtA6jMqcVqAUm8DAzRcs7NY=,tag:IhtNF1WOVJzZ8X6HVGHufA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
