apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: kube-system
type: Opaque
stringData:
  adminID: admin
  adminKey: ENC[AES256_GCM,data:v2+sjxj9NhAhR20OkW8Sm3+VKfr4RkZD/2BkQpUMa/MxKDr3zFVcSA==,iv:9AzHBQZ0UMhNj5P2IjTR8gcduszNYsFUpIAB7SiBMSE=,tag:F10lRBcbi/lJYbaHig0fKA==,type:str]
  userID: csi-user
  userKey: ENC[AES256_GCM,data:PcP9auxeZ8RTYYxmHdPG1OnxyKsTm9u1/3QapN9SitAkCf1S37ECLw==,iv:OWA+SJ1jem6WByahP+XCtZSylF0ScT1xUgEVUQEqA9M=,tag:885rRDMEyiZFsuC7jT8J1g==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMk00R3VHQVJJK2h2L0sr
        Z09IVkk1aWxPYmg5SHBqcnUyL1hZWU9xR0hFCkI2OTQxcVU5elQzSzdNSTZLd0U2
        b0ZPUEMrL3A1RUVSbjY4NFlxS1Uxb28KLS0tIEJ6VTdwR2d1MGxPSDh0QWlWbkk3
        SGtBcnBDaCs3djZrcnlTTGhmbEE0WkUKJ0pwNfbko67EpzvLA5LiAU01Qks45e/X
        PB9NtFWMh4cnyyjYqzpc6u7fLprEzRVsNypwxduILyBV56Wgi2ZE1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T22:41:39Z"
  mac: ENC[AES256_GCM,data:TQlaQ2Kx2HXrfTXlSWieStNTjS2ggcHkHawCSpdxG4RdHJfzHgD1ZZUqOLFAitxLJgwFr/ZzmXFnN1OPk9hZrw819WwGKIr1Kye+8yWDv7yI6N6u5fRfOrYzf9i1omg51knecRcrRKdkqqi82h1Kysqj3mNLkW4L/5veZ+v/l/A=,iv:u9xhnpWHuhHsi/018NLXaNu9/FH0kITVTADh0yXjqmc=,tag:FAKZC9y9uJQAzrkMJLksrw==,type:str]
  encrypted_regex: ^(adminKey|userKey|.*Key)$
  mac_only_encrypted: true
  version: 3.12.1
