apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: kube-system
type: Opaque
stringData:
  adminID: admin
  adminKey: ENC[AES256_GCM,data:imY9kgns4PH3XGc0lzaCH7TEC7/LWwn+z7mJUeN9Fqpxtarr/CAxGA==,iv:Z7PcMqxGlPSCcnlNR6fhzzGBlXHeZCZiIYOneuq1ifs=,tag:lkyrH3/Pemt9g1oB/3C8sw==,type:str]
  userID: csi-user
  userKey: ENC[AES256_GCM,data:EaQ5Vs9molbZZ6DCFoxVIarU3vflirSf3TTUx6tewIx+uPmFd2TDBg==,iv:5ANzLX/tsraiANwZnMz97EAS6ZE1eDafcgaSkvpn+Uk=,tag:wO5+FwJIvdMYNTmX/r2tdw==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMFU5akU3RUJ5U0tkTjE5
        eHpzajNuRWRZQzhWQ3Z5VEw3eTFVWGRZSDE0CjNOenQvVTRMLzdQNEhYU1FnOEpm
        WHBkVzNjME41TTJjM0NtMU1zSW1IeDgKLS0tIEtsK2JzQ2hqdjFlMXVDZXJhNTRT
        VGViczBEZVFwY2NCQ2ZzNE9YNU0yMW8KSzPy9mQyMacEvbUvCcidgWUfKALr87vq
        ZyOjzUkpIDO23IWIpym1a4vkhhZU7KdpHmKFRI12saWARWA8DEAssw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T16:30:55Z"
  mac: ENC[AES256_GCM,data:HKB3c5xPouZRjW9Jva3rHZxH0m1j3mZH/gHWILglRdzUQbuCCl4lHVlyjMpe0eOPo+KHk2nraMgfs1KrY8j2SCXiddNWDh7gLpDgbP5WQlmjHwxJ2zcUrXh1TKWl575ZWdDD9Sse4g1A08dsuVk9VJ0WGJX2YD7m+Djs1egokGg=,iv:AEOnB0OwEc5e4CouLt3yRJOTQgsWgGBMK+03sk1BV6A=,tag:iHGZiXitdGSda7Eu03bPRQ==,type:str]
  encrypted_regex: ^(adminKey|userKey|.*Key)$
  mac_only_encrypted: true
  version: 3.12.1
