apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: kube-system
type: Opaque
stringData:
  adminID: admin
  adminKey: ENC[AES256_GCM,data:WTXS9ANlbOWEoYNEbw2zMGOvUW06kFEWGghUFDF59xauq8aiDwnUTw==,iv:UzztHAmSAJkzhZKuOBhoIZHuz3dKRUM222aCRSuL0P4=,tag:9khvKg1RR0YgJ2zi6Vxgog==,type:str]
  userID: csi-user
  userKey: ENC[AES256_GCM,data:MuA7uJB+G1TytokKUqwJfzGX4Im9FduHplWX+7x2eh6ZKlieTcoSWQ==,iv:/+cvhYAPLVLdxvsiNfJ4hKgtFi5srg/Q2RYi21DIh80=,tag:TWo33bYyTXInPyt4oT50Lw==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaWdzRVdnNGp1U0VVTWRq
        NzZWSVI0aUFPL2FVZURZb1BEWUc2S3RNUkZ3CmNxR2ZLVURkTzVidkRDRGlGbEQ1
        UE1PMGtBOS9Tb2FRU1Q3UEZlZzlpWjQKLS0tIGhvM2F4dFVCeGRLSEs3a0lPNXFL
        cFU2aUhxdWtDWWJ1Q1ZjUnozOEp1NTgK4YdxVCCCvjJ4LcjtZro3e4aGEPT/wYrG
        5P0fQ73k7/k5EsEujPqeCu9F/ErduuRBeRn/MkF909KERh3799iRdw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T17:15:40Z"
  mac: ENC[AES256_GCM,data:meKiGJOnfKjZMsubs8QQ+EU3oNrTkZD6tksxhmTqb8bbTDNdSfLoBHF3M1aoA+1VY+SJXPmX6CVg+izU8mWXfoyEBpu+qZxzKFNkc1NgYGSCZpOyw4IGgcxpBNnzK4qfVbJIY4C3jVB2IB7rbvSYiomEj7E09uTd99DGqA4dOxI=,iv:kOPSkUeVBKMK5QpkpHe7mpOUyNMcR0y84SF8IJr8WdE=,tag:Ig/AMWKxAqB5/ew3WyCLFQ==,type:str]
  encrypted_regex: ^(adminKey|userKey|.*Key)$
  mac_only_encrypted: true
  version: 3.12.1
