csiConfig:
  - clusterID: a74bdf84-c6e5-4a3c-acf2-6c307f5c15a4
    monitors:
      - 10.0.70.10:6789
      - 10.0.70.11:6789
      - 10.0.70.12:6789
    adminID: admin
    adminKey: ENC[AES256_GCM,data:PZ9yuJcQZTcFkwSmOJBapmknFd/p2YPNrQn2Fwi31ns3XpM84zgnqg==,iv:JSvzK3u/ArcuFryu70xqWz9oJoQjKW70ctKNdO7Br5A=,tag:hL/sxs3GtV9FWpMKHDBrtA==,type:str]
cephFS:
  kernelMountOptions: ms_mode=prefercrc
provisioner:
  replicaCount: 3
nodeplugin:
  replicaCount: 3
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdVptYVhidHd4d1RYSGVB
        cVk4SGtlWnM4RUUwM294ak9KZzY4OUxVRG5NCmxWaUFjdUt2MldkdUtMNU5zRDV3
        Z09jS2FGMTIxWTZwSWJxL3djNU5xeTAKLS0tIFNvTU03ang4OGJwNlMvMkxYT3cv
        OVVGbWtETVhkOHF1ZVVHWGtVNHlURW8KAJEIUoWtMqwY5+uOApa1Udx/zmOq+2g9
        cLidcLkOpnE0bTJcNKtfJXp0NiX4oVKOkdCgdcBntTgD14a9ACs20w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T20:06:36Z"
  mac: ENC[AES256_GCM,data:+miiSXmWftMFkz0qEnJvZhryvWVv/VMTlxuOz9yYdEppjBvFUU7WRivmbHcFTlEjO9LuQxrZWs7CTpBPE2pWLIXMuNEwhYpGZiSTxjIaJtlDayagRpXG69SCMsOuSd6gL0AwGhUgP0+kv08TqY8P4sfh+FK5WHMsM4AZCwPgKoc=,iv:xPaNJ3iWBbLmsjjNI+74tHaIoUKeruNdBrwaFiGF+4M=,tag:yuAFiu/Re7sQt56EPdtByQ==,type:str]
  encrypted_regex: ^(adminKey|userKey|.*Key)$
  mac_only_encrypted: true
  version: 3.12.1
