csiConfig:
  - clusterID: a74bdf84-c6e5-4a3c-acf2-6c307f5c15a4
    monitors:
      - 10.0.70.10:6789
      - 10.0.70.11:6789
      - 10.0.70.12:6789
    adminID: admin
    adminKey: ENC[AES256_GCM,data:ZNGURZamMQDDrGjucn5fEUQivAQKZOS1SDljX+CphGZXI8s5AOEp/g==,iv:PW/4USOUqjBExM92rCI73KH3jMWBk83LdM5543+2kGs=,tag:jdbq9+Mr2AM2Rbbe2ReXwA==,type:str]
cephFS:
  kernelMountOptions: ms_mode=prefercrc
provisioner:
  replicaCount: 3
nodeplugin:
  replicaCount: 3
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUG15eEYxM3VnWk5sQkxj
        QlNBWXVaeUIxNCtzbWNkRFVhMmlQK1NzOFhrCmZlMldmZm1zTmRpUEF5Q0V5bnNM
        NlZUZWovczdpVG1LQUJqUFNOZk1MZ28KLS0tIFFseWJuSlBTMlhSQjNGd3o0bDhY
        cjBNU2tRczBZZjVDWEF3U0FrMWQ0cWsKcPKqiaCD+71SAfLrLWRATAjExroJ183w
        TdDuv5Dx5TqoTYBz0dgguUEYHGRWWBhDW9BkWwTcYR1g/F9ockpZhw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-17T07:48:13Z"
  mac: ENC[AES256_GCM,data:YM86XjHEyZO4tk+HwZHU6mtEwH7Y7bscdU97OgKxAsyhd5aNZ6OiBzAZGof/rT4vRMx1zmz3MuA6up8FPFAaxg8KjrWJsFfZQ5KtPefGfbq/5hP8sDtS7tdXy9xHdOXNDUz2JamhtteNbgFPaHT0F5MRdIIlH6e2CaxvD8aG8Z0=,iv:ohOMLWvAr3Nl+k8omx55frzI/d/P2c/ZP2Fa0LE1yZM=,tag:/LPTgHC5nxeT+l8v19S/Wg==,type:str]
  encrypted_regex: ^(adminKey|userKey|.*Key)$
  mac_only_encrypted: true
  version: 3.12.1
