apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: ENC[AES256_GCM,data:hYpe,iv:FsVWRmBOBcObytvWqgUMBSvqru2zsYWDsPlQD2VGeFs=,tag:WmvMJhmPAA+61cEV3PBAnQ==,type:str]
  url: ENC[AES256_GCM,data:s8RuKszlR/E0nMkj2sqEL+f8/n+1sXpZc9pUuuPsU9tJZ/g8AUs+13rrs8FBqf1pwqAvIx/QdVlj3FZH,iv:bkww+M6p0k/IqE37zWsDRRbdfrdFUftufDAs188c1CM=,tag:uc8JrP6CrRBC2jkLA79Leg==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpaUF5dGNQNGJPQVFobGxB
        dTVNNFIybnk3eng3Qk5rQWRjcE9QMzhsdXh3CitKNlhjYXJTTEJPbjZCWmJxZm9K
        SmxJN1pWRTU1MWRPc1pyZ2FVelFMKzgKLS0tIGlVdzJCZXVPYUMrL1BsUzhITTJB
        a0pLWVBPNzVOTkpXSlB1RUNrU3FuOHMK2JtJuG7W0+v1Y8222dZbtU5NQeYNikRA
        151zYf+lx/PEqSkLnHVHUcZPiW8BFK2RJQig6S8+C3e/SQLDR0OYmg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-13T20:44:14Z"
  mac: ENC[AES256_GCM,data:s2pLrXQ+NffJaWMqvidRJCY2IFmlNEai8nDphNtAThsa4GqRRAe0nSzku1FyMukuc19oMFBfDpCFttxtqd3vmBhSct9MY6jI3Swe7iXPywKAbbAVOltFJn3/3pXe9/tjK7D1KfLLb35RSB0tHN6N0PtozVYuL89QBrTrcaoTxkU=,iv:24y0yUwL/j28P/Uisy+/O0cXj7uH9s8tHZ6xT7+KWqI=,tag:pInvYBH9FjkLeZZWL8XHWQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
