apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    privateKeySecretRef:
      name: letsencrypt-production
    profile: shortlived
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - krapulax.dev
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWWJZZmE1TlRqOEdSYjdz
        NFByMml1b28rb2NBMEtuNVVldUVPc2E4ekF3CnpNbnVOcmNxbGNEczFkN1ZGSitP
        aDc5VnM5Ums3dmlNYU1Xczk0V3VrTEkKLS0tIEJPcG4rVCt0Qml5RC9DQ2h4NTF6
        RjgzcXhhU2E3TWxkc3ErekxJWFR4TlkKQWkhuChkCFFWKzhY7ncC6r9Q9EBUSefo
        md0F4ZNsFJriuizxaYgVk0B1krAPksZSv6B/LdbOUJHwTrCjiRCXcw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T22:41:38Z"
  mac: ENC[AES256_GCM,data:EBQAnus2L+B231p8gAmYKmDMnIJemrSHLxZeGOOoSpUMx7TSOEoRhh6db5bR0bXpbm7/gvZj6MaFXD4U8XEyzJFeR6BA1j+CBOV1nvQFm65KNadtHt6wPjolX8D6kakhsOGdp3dxP4EqV2PeY3BFlIpl2Lp8NfShny1c1yqs4JU=,iv:t41AzeyWjVnrCGbbbyTxUbdTYP7fQvc9nqeborMk8m4=,tag:9qv0ZeEjC7SUaNs+l19EBQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
