apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    privateKeySecretRef:
      name: letsencrypt-production
    profile: shortlived
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - krapulax.dev
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQldvSmNCT0U5V2pnSmNq
        SXA5RnF2Zm0ycDlIeDZ4bEFnZGdjVjAvQnpFCnJlb1kxcUc3aHJ1Y3BxdzJDUmo3
        cnA3dndkci81SXFDOTd3Vy93QkNuek0KLS0tIFpIQzQrdktXVkhMVUFHNmRCbWd1
        NWZZRXB5UW5PUThtQmhmRzY5VHI2eUEKs7qduk2FEluACM9aVSDDccL3GsqmZji5
        o0jR7T+0Q7F6dgWneTB3B9n0N38FQNxIyW6ldBEM6HO/gEpJ5CiCWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T19:35:52Z"
  mac: ENC[AES256_GCM,data:TBdM609xFX+uca+HdZl9p+k8Er8vgClRB2VNp9eeCVPC0cPgHiwo1UbSoy6dx7w4/7v6KyoP5OIYv8K00p8qbZ+uUu4GdzRX5t1A+AIbWweRjwAQO897XxQTDGxUIwK3JHoZ5xngtkP2tWoEhoYLE+DNDIuKx3j04ZSGjxI1Bzo=,iv:tyfMLQoflpPcWtjUgVIhegOuPnzVe31FCaeKhWtnMho=,tag:exXAZbR2LI0lcoi9guOM4A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
