apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    privateKeySecretRef:
      name: letsencrypt-production
    profile: shortlived
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - krapulax.dev
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISHBTdVc2STlnQ202dmZr
        NFpxS2t4OXhRZ2dFWmhaT1BLN0NKdk9SelJRCmloV2J5UUlZTjU5SXgrRXlzdUE2
        NGM3dUY1bHMvdEpEMkZBczFVQ0tUWG8KLS0tIGp1TGdtcUN4ZGJzTkZmUWMxN09T
        VXdVRHhuR0t3WTh1L3I4U1V2RGRZaWsKpm+PqrPmI1CsAzPzqN6Pgo60KN5M0vvl
        dwVLydll3BXM4l4WoMXndPFhh+IOeQ4b0CcnfSIoupjAA71FFiQchw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T11:36:10Z"
  mac: ENC[AES256_GCM,data:t8WsQrwzeFnYql5EgjvAF+dKJDrRzQD0hg2enGfdbWC9dltrwNVlm91wZX9hFOsg8Vklpo2PWC9f/2vWWSUvgqS9Ika9EmuV9JpddpDzrYrXsogM0X4eMFti3vyj0I/rj9KC+QwbpebHeFEIt6lqppQlhQ84EsFGQ7jpT1eos4o=,iv:ymNysluBiKju8qANbYDP+fw3IJsthfNjsWytgWKGSf0=,tag:7YU9rLux5ay7TLR0sHW0Vw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
