apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:KaZ9FWKDsgPqChuiSdYXygKpBl8tTfk8R0WdlbotLbU3qHFWEdJ3Uw==,iv:fboTmZ3v8EaH9iaj12tqzqQuU8uvdItk4n0L1IbNRdQ=,tag:ppM5GdHVSKOFKBrTrYCQpw==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMVU0NUZqL0YwRmhtWTUz
        RjVzZlFvS2FSUzZwMURQTkVwLzBITWp6TmpVClF5ZkZJOTBqeVV1ekFidGxaMmRZ
        dVJrM1Z2YzVyS1duamtJcUQ4SnNVSDgKLS0tIHJrUHpkcHVoUnJXclNvNDNTeVVZ
        MmI3czZXNlZCbjZ5bjZtbEo3ZHZ6Qk0K1J/eGqLmvDoxO87hCvtgo54A/8DcyJv7
        55pqmTCUs7fyFPApVGuEqaAfQJutjnphsIJwuYTsW3LJ0LvJ813HRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-13T23:12:39Z"
  mac: ENC[AES256_GCM,data:YzQQcAM85ysmuPZZ4LFA9wrSyJNnul+Ohk4M5v5W4pT0m78u7Q6xZ7QBc2fWElvSJy72SjvzCeVrEHMCJ+2Ce9bnFHLouORJnCP22WjMJvkvaBEFTkH1hJyoz3MQIezEKkusyNMdGAvY7mXb3O9m/bLtxP7jGCz6onu0SmcFzPU=,iv:xoefMsTA0YPvoTrQxZWnxykOoR+dH0GlIALOlDM9IwM=,tag:gVHevisoDm206ZhhI0ypmg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
