apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:68BfLaQFA6FvYZHqMZ/en2f4l8J/3PsvrUVzTStay+RmwXXgRrZxpQ==,iv:uoLLol/gYLfwg8EonU9bqE5l40UjUofrFsOmKIXIT0U=,tag:wSwH8Xx2yOdMlZdubTiW5w==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybUVRUjdVa1R6UElUT0dE
        OEdTTmticHhsZ1dZY0F2emFMUExPWWRCQVZrCmpOWXZiVzlqYTdsUGJWamlSMHZz
        RWc5RkR2cW1aZVo5SXZqZXFIQk1wNFEKLS0tIE1FWDk1SEVzWXdzZmsxUDZham15
        MmlFWjJvZTdYK2I3Q2RvQTBkNXpOakEKB6R6eKO75FkZj2zajzINOd94f6yNQ0bD
        ENgKAIb+/k9g52lgSo1Jk5ismS9wtO2pbdT/laaJnZM2bA21b9MO/Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-13T22:54:34Z"
  mac: ENC[AES256_GCM,data:7C78dVzcvD1wbRy8CFfiT60e6j3WL+hM08NHRBjKUWgjC1zafVv+p6QfZw0caEuy2RRQHeN/6fWKnJJFm2YPwgd1+fCfYVoeRa4zUfwK5XYsLstdBPCcMuC/zrkwQrTcIrt4KE9ybhUHA5t58SoDNe37qppiBtKvqSqKwoecZ74=,iv:DlX0vdLBPdcsZganPrLTQZwbsqaNU1mbBgoGS7kUMA0=,tag:4lZzK0Xb/Mta8/gDSDqQYA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
