apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:ksjIw8E9AqHg2QiBtWFMc5aR4p6Pwq8/kzA+EPRnnDkp+yiLihI1nA==,iv:ldJ0jKKhwSyOjdXTFXknaQw8ren6ALAkoDdTmVhRxvg=,tag:LIuhwqvnmFbVRkWvC2XU6w==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBac1UyWmhOTW8zNUZBbml1
        N0VWMzgvaFE5cXZjODZuNVhuS3ByVUZXdDM0CklLcXlRc1dqWjJjR0ZrMDdEQkZL
        aDhXRlFyOElFNUJWam42YzBFSkthZ0kKLS0tIFdMcnQxMGsvRXFNWlRibm03Z2Zt
        VysycHVOTmVPOU0zTFdubXFkNGszY00Knf0GY+hhiGyfaspSzZ4hqHcG4kU52Ado
        pBF3uJEXTe24g1WfumkHrjCBS+YWH8v8cSAvCUcz3+J08cQ+VTQ6cw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T16:43:43Z"
  mac: ENC[AES256_GCM,data:p2aQdXAPzhDkPIjGsmoQh/oFgWL57YszAiIaNaYF2JG/+gp3t9Atmmo+mDJjhzYkYMMtj0I2StJGSNAMTMNol0czay3m2XvyGCXo+cbQQaHrGQo/vfLbHBf9KzfaBCusvZUSFOQjqawLFvG8VFiXs1Il8eHVKqyDOWjMWBcJGbg=,iv:HU3dv0/+8LoTYvkVhhRBLeMqkUc+qoEra9JDrge/zbo=,tag:e54RKfbTW1ZE/1qRX8TTmQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
