apiVersion: v1
kind: Secret
metadata:
  name: doppler-token-secret
  namespace: doppler-operator-system
type: Opaque
stringData:
  serviceToken: ENC[AES256_GCM,data:yNTIh82hC7BKzpPAfolhQSSKJkzQGkeF5GiVegHaoE0TQmQzItEKtp/INROAkr4+EHfa4cc=,iv:bi4U5AqeV5yiXYCkjrhzAW9lDJf2r+ckGy5rRQDxZLg=,tag:dWisYO9jz0L1blufXpvksA==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUW0yQ2xsNm9oQzJOaEJP
        M3laTHJaN2U5dkYzQU9TRTQxaXRkbWRmbVUwCmRCRjk4bndDZjNpMlF0RFMyZXpB
        WDVDdjVaRFNHNWV4VExLQTNEcVlwckEKLS0tIDhVSDI1aThRbWFUekthQTFvSyt2
        UGNuakFHQXpnQTdmc3EwQWpzWW5HaGcKf9EW/FXpQULC6+6Feb6cz+4JvPxs/QOj
        gpGMaLqcH9M7cch89GifmRzLXk3vVYMkzWqbeQ+eQ/KYtvCY3Gm7bw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-17T07:48:13Z"
  mac: ENC[AES256_GCM,data:Q/6eL/tQrcg6el0kcm1Y8mkqVC3Ouc4u+4jsriH+43I23Wi8W0FDnkcMtIiQa+XeH8oZmgtDSbvjYr0fT7TkOWmcQN6na/1pD8vx51TBzjhFgx3obRptO7ANhM6IDMCMVmGEGHv7eLabHok13gi4XyPu+y+ALea9jP/nQeSoIsk=,iv:E5807f6a4EtpaZqbkteJTgBKUSxkKG15VmiTq/lgoTk=,tag:3f27Ez/xTfsx1riPd7NsCg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
