apiVersion: v1
kind: Secret
metadata:
  name: doppler-token-secret
  namespace: doppler-operator-system
type: Opaque
stringData:
  serviceToken: ENC[AES256_GCM,data:RiNBQhx6qwZepfiSDSK6/Z2ajlIddQtmShCd2/ZqnT6XoLL4of9xMpCooZe+NQsfWuVTaes=,iv:eSIwVWz4WO+nY6MdlOyH4T2y5Ce/2sFqoAipbsebJw4=,tag:dhcGZ/EPYi1vgGdnu/YdAA==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UVhwankzWmVPUnBvdFNn
        RjNOd0xlNTdVTjVucHViVzFYWGx1dzlSUFRzCmFkSDF5RllCSG5nemRzYVNxTlgx
        Mi9zWVN4OHExZll3WW4rbStVOEFaZWcKLS0tIEYzaUFiWDBFcUVZUXRjakNXNGht
        WUZLWE1FMFdNOXUzcHVkdDdpcUt6L3MKyWc8mk3JBjg5CsV4dC1G/fHyhN8kT/9c
        yud2bsbO3qb0e/eIT2LpFwuRgrUOjJ/dikvMisFjOwbtL51yehFRPg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T20:06:36Z"
  mac: ENC[AES256_GCM,data:G1F2x4UZ8ownIcpkwefwVLhB/HI669hqyunZbM1lkxaxU4mqud8B+Q3lC7pshOgAa+BDHGr3dVx3c2lJL34GWUmHkIg8MeRluw+pT/XKqbZhoWQHRw7lHKiaTGWkotDS7oQOlBxS4f2Hdr26avwhG5LBli39CXVsberxtvmBwLA=,iv:kaJn5vr6Gigct4WS8WIVsfsiWtr3ljWghrbdh32SPUs=,tag:XsuyCmqI0/iHUHVykMcHNA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
