apiVersion: v1
kind: Secret
metadata:
  name: doppler-token-secret
  namespace: doppler-operator-system
type: Opaque
stringData:
  serviceToken: ENC[AES256_GCM,data:ZIFaPGAkwuj3AHQvmpDFb30TJptrfBqqMalMFU13qiNtnwEjMzGYUwj0BUGzffIL0TBXLEQ=,iv:taMIYTSwWbV53309TmjjwlAAfdkhulhmP7nxjE8ulJs=,tag:7tm7CByoDd2A5V8rcPdy6Q==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwb29Sd1ZUbVk2dzBDc0Nr
        ZHJ3NW41VHJ0STN3Z2pOUVp6R3dud0duQ1FJCjJpMDNuU3N6MTdtRDlzSVNsUEV6
        ZkdYdUNqYVEvS2FDVXJsTnVNRXRoZFEKLS0tIDlFQTRqRFd3L0IyQUhqSEs1aFd4
        YkpUZ1hBN0RYdmpybEd0bU1hVk1scUUKeVZNpVgDBotNIwY01aOVJJjogDI1+QWG
        6SgdIuMSwBMe3CFAM7ORcky3T69kLaxzBo7TbjerrnFdgO/XoSx+fw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T19:35:52Z"
  mac: ENC[AES256_GCM,data:y8i2VnyeD474kiK6tA7ZjZx5I7XFjryNzOuTr+sio0oRDyR/8sw8PzjQOSHL6DRajL7Lk9pLPsiFben9DNen+FuQ05+J5iEb0HgkEwPHqhU90FlIyo8n0p0sulzZR8T9z7/cSS7H2eq8GiVKCM0phWowQvxb2pOXtxJXkic26/0=,iv:UHy0xIKHLVLjPWdkPe3Km9586HCtJK3YDlRM8zGuVFk=,tag:yOin1n0I4ZKS7LsGeeWIzg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
