fullnameOverride: argocd
configs:
  secret:
    argocdServerAdminPassword: $2a$10$r0U.A7.56h6wtSWetPZVM.r/Ez4YlCbmjMTE5ZUdyoxJrNu44Zde.
    argocdServerAdminPasswordMtime: 2026-03-12T16:43:43
    githubSecret: aaebd543422ed4c2f5c8e89ad47fee36
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TTdZeUUwRElCWUd1TkhZ
        cXdQSFJab2FRczNyY2NhZVBsaWc1d3Q3NWxBCngvdFZSQ0pEQVN6TjllbFRSbnF3
        eFpMdUJwT2JvUjl5MXlPTFZUQjZMbTQKLS0tIEYzQUR3WWtyalh2SEoyUVZFQ0oz
        ZVNIRTJxMHNmU1NNSGN2c3BJR2c1TjQKjI8qFs1NPeCqiwUkIqd0v1Bs4wKZjkXk
        5W9zmsJQs4dLkjYt4+4cs7i9lysW+8+JS33LWzEQQE49byUw2jwbeQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T16:43:43Z"
  mac: ENC[AES256_GCM,data:PJGGIZ5YUmLo2jw3z+m1usA2ynFt4VNIrjzWNhM7HGh0NWWoOICGsFMLJmGVrJTd2KM3Ag6mpRspzongYBJSJYjYYtW4Qs6rZRKjcTy3421V2/4XOudBloAXLdxwIqqtfCewI410AABAhIjpxCpTpeLcbtrNZRkQ+h05F46XfRU=,iv:rhhU89BG8bmozL3rPkpwhkSIFKCIC8/3vNc43tvEPIY=,tag:weFS6fdp+21iUMrFerd1bg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
