apiVersion: v1
kind: Secret
metadata:
  name: helm-secrets-private-keys
stringData:
  key.txt: ENC[AES256_GCM,data:KXmHHRhwLWNSsFA89/X/8fEpWYhlHwmcF70/+aLXBSKLQa/aB1asNapGjPxJaQXmJQH0M4W8EVc57Lr+5WRdWkpIWyybIoQzo5Th,iv:ZpBiOw95p/8HydOAjSgknRBMTI45HxzgdOzP8zf6ugM=,tag:Sr8cZgOzgYc51ekQA7wfMA==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTmRJUXUwOWpMYmI3S1NE
        eDh0TS8zc2t6VnY0Sy85Slcxd0MvUFlURkJ3Cit2elIxbzNoaVpxSm9mR0huQVJC
        TEVJN2p0WkJkWGtLK3RKNkJ5VGZlaEEKLS0tIDV0ZmRCZjV4UVY2NS9JUmhHa014
        ZVBFRGNhQVI0MjBaZi9OOTNVVW9QSm8KVc2W7Z79qWGUNzCu+UqTn/v/LhYCF72K
        To5VvbHdpV0O2zG3mNuZNiVOVy+kKEHjkZsWJoAg1l7LvQ0vRaNWcw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T00:32:14Z"
  mac: ENC[AES256_GCM,data:B9WmIN1csvdn4lkY48iJKYXqBmyeAGj+90TXTLCRIk5HopS+NIkhHYckIX6S+7u7w2sP/DYlE/z1rEF26Akqp49C8gY8xdKfr8TQmyx5NRqoYMb6gs3P7CT82xVWFDRoxMNf/Wr6UN8SL2crgBHDglVIT3CXlQhRo7CQlQXLH5Q=,iv:KTdsu09r8dsGRhR2Z5Xp6dm7w6Xr15eutIDw4Yh3VFY=,tag:1rObiqTWfQSaYRZ4m3pJBw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
