apiVersion: v1
kind: Secret
metadata:
  name: helm-secrets-private-keys
stringData:
  key.txt: ENC[AES256_GCM,data:cN3NgNSuJUPDaWT5mCMW0dyXrdXgu76nKZgI+DEILD/Yruky2YE3QaeTsPDoG1MRtPrHwaKWy5syFS73mV4W5W3VlnCT21OxdL9n,iv:dkprK5TXK0eQZ0qM3Jkgv4TTLH11gW0vTSqFN+po3J4=,tag:KiJH7tmzPbA4FzjrtXGFgA==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NUt4ZnBuUDFqbWhtVFVq
        TW5qa0w1OFh5UGV1TzBXSUdmcDFUdWtZT0dNCnRBRWx6RmE0d1YxU3dYelFRRFRF
        a1RxYnNvYW1ETzV1UGI4N2c1eWJEWXMKLS0tIHp1VUFQSm5WUmhTZzZuUmUyVU5G
        RUFEWitDamNYLzFkL2lLRjh5NnpYNlEKlnRnfwh8a7p8J4BWDyCupI5C43rvsTOc
        rGaloubNjnmS0qrLt1GL9eHDbPFa2C8YUyuFslWqWd6PZAXn0eB22Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T15:42:21Z"
  mac: ENC[AES256_GCM,data:Dr5QO7KnxH3MZaJSUfzDf/2FqASRO4p2asrq9BpvzckyIVEKtWDRbjEOaLLy9mximbYaMd6VIc99bL/xqKMZ/b1YmvVQ37u3O6f5A9Yfupj8Sbke6GmRNkDh9HiyJ1Uhhg3n6yjzuV+bLsrbmoGUokLtqIKTnBg5WV4YD5Uw7Ug=,iv:7PN58n4EudidGmW1RVc8P3CFH+BzpYPlSFBOP57405Q=,tag:dRcuS6TtXuiy5UXRV2CIig==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
