apiVersion: v1
kind: Secret
metadata:
  name: helm-secrets-private-keys
stringData:
  key.txt: ENC[AES256_GCM,data:fcODzvzr0dDGjewYz2ZTYcqy1DERLdmJksW5N/NFUVSSPDJ3gxb/uyGNFBkF6TY/o1Xvm406TK+qMMFYRbmgfCXsq8cF1zq626t6,iv:WMWoay5dEz8Zjdtzl8CJwWratkvgnit+2+t1NVoEnNc=,tag:1D1DP9JpdBWtahqeJCoz/w==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVys2YmkwRTh6K20zaXFn
        VTR5UEJ5ZE9Hb2pPUElLRWJ6K0xwZWc2SFRvCmp5QzhXek9QL3FIbFVSTktQQjRT
        SmhrNlpMZWprbGpPWGEybUVHZmoxYncKLS0tIFQxL3hOR3JFYXVZcWJDZEh3QXp4
        SjNXVFFCYnpRbURtYnMwVmJXYXhkV0UKz2YfnwjQ9n0uLKiKhr3tLCmke+AsxPt0
        NwL+9ogzAgFGTmOTGg0Od3X7Sp8oLxt//gh92YqT6A7ChEiEwqfUxg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-17T07:48:12Z"
  mac: ENC[AES256_GCM,data:BGYimoraI3CA2MYwsEAm6JJGVhXPIkiqzNKXU82lJgLYrsZS6O1Q23H4J9rtBc9zkAx+ZlTkSroA2FlP5d4Ocm/dL59aDVvnPJzeWVvHP9pvctjz6sTZLnTj2eMRFpa8YFEIpbAjcXEfIrLx+CMyV3GeVlE15giH44QNGBwn2LM=,iv:nhna5OwOddE+qarkVplN2g1C5bMDZHBsaks5/P37IxU=,tag:JwdUY7G6DYLRXidVKDgucw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
