apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
spec:
  endpoints:
    - dnsName: external.krapulax.dev
      recordType: CNAME
      targets:
        - c153a412-005f-4c07-8b89-34ec5628005a.cfargotunnel.com
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVFltK3Y4ZXcraEZtTHhL
        cERoTVFuUStsaGdObDBnb2JqUjhPYkNvU0RjCmhHQ2R3NmVUdmR5b0NNVUcwVnVj
        akF0d0lFb2VtTTRmemhnckRiek5CMTAKLS0tIERXTERRbkV4NWJwc29BcWJHK0w2
        YmF3dEhjYWxJOXRJSHJROHpoWEhTR0EKHKc+UmoiQx1lM39fYGwSn5NZiA6uY35r
        i3wWpk+cBMD3WE6uZ6XrKKI6CKw9HTzTKhFw3Qz4DQmQxrCw1mo/PA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T15:42:21Z"
  mac: ENC[AES256_GCM,data:L+HJASNYsuj09nGGZhqXbpo5KP3/YDSw/rLFN0s6kZz1gkE80+3/kMdD3sXSq41wrNThN9u3akyw4f6YRIV6TWPBIWRnTevYgXYjxPxoZV+FurNyQPfb38o5okHpQWkN04bWQu98VKSUgigWFSYaA3m3bQwe+PlR21PSL3Rizy8=,iv:zsxuSYfcYukPseq7HlXlt0Zr2PuH9TdFITufI3OFwB4=,tag:OUH216G1PnE1iTPMFzTS/w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
