apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
spec:
  endpoints:
    - dnsName: external.krapulax.dev
      recordType: CNAME
      targets:
        - 096b810f-27c7-493b-9b9c-5e5e4749830a.cfargotunnel.com
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVm9PVGFIMUc0WWlGSlRm
        RFdGMjllWitnSzFLNVdLT1JBSXNGeHRTK2dJCnBoOE9FdWdjdjl4Y0VoN1ZaNjk0
        QWVHTFFIdUxxOHF1Wm13K0hNaXVaOUEKLS0tIHFadDc1dVhnZnhOOUd1ZitCZzVZ
        NVkrS1pyTDNJUXRCOFlkNm5ITWYyTjQKMDhCvgoyu5ZbrO16soI0Zsc4cxiM5yxc
        cViqFSGlBtG3iZLv4PIDZcd7VrJubDmC3hrXB/uI456aC7WIMbcFdw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T16:43:43Z"
  mac: ENC[AES256_GCM,data:/6VcV9ll4DfZ2lRsIQROkjZL0xJUerOl1QeE7CzKWcdhPRWjCpGkBWPAVV1MMDRyQICGvK29sGHPJyAfujrgnUeLuwtevbuRGv/VsnFrV9qZ7vWOl1XUYoBMSxZtuHppin8G40RsBZ6vMESj5TutEUmjgF2g9WWHZb8/Us/FQh4=,iv:zI29tNDJwKB4/0UIfuEILOzD9zdMjRrnv+j419fm/5o=,tag:Z1MFui0CZ89I/mZRMmJ3jQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
