apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Pm/pIVTZzEZu8XXQBBly+JScWR8sceHUFT5T1bUfP3VbbwEJuG9FYeMGIrMOC4ko8+3jKtoyHPj+3EpL0lxhRgnuZYYJaRm4Nsqx9XEtirJPqeMPpL9XyrDqM4hXET8qq1aYfXJsXh10jaWWV849NeVXLl6EldVrXdPtJ0j4v4EJdtVwC/FIZd00zohmBrykIKsFQkAjZUHHTFpajKojn+3Ca+bgTzwUs32pT3OXGNl9H3xq,iv:HDPJ8prf55Y9paXYyTGX/P4j3fu/hv9tZiq0rj1vano=,tag:dy8a2MOOVoggAxuDWnjuvA==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdjV1b3JQR0VSRVJaSGJy
        OFN0WGEwNHhzRW82ZlBkUW90cXl4MFloeURNCjA2SVlyTW1HdlBRUURGYzlDZ3VE
        V2FXRTVaSG9SQ0RrQ3UxWFVsclMzckEKLS0tIG81UnBKSjhQMGFDRDFLKzB3d2pn
        aUNlY2JNVnhzczIram5YTkE4ZnMzU0EKc++74hLiQSeF7MchEicKugidP4nlGqKv
        Lpw3TaPFawsGGu4fpr3DZaGh8WTArJ9DoHaA5OrAY1u9m6kuPzI0nA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-11T21:33:02Z"
  mac: ENC[AES256_GCM,data:fl1QhOdflly8bu3oZAHC6LsBR4cgk+/kZHaXwWoqV68wxayiaHolbaVR7QMfEWKAEuzgLDDoiTR6GxZf6D/UTc/Q+5+O0CvGc6oBi5KAsCuuedPuDkAjgczl4t2oITNAFQPw8ZvdqzKkqv3jDYq87gGIGqDL8WbGf/ke+2q+V0k=,iv:S+gnpGSc60ylqYJ4HX1q2x+xAAPnW+oxXvea/SzLWpQ=,tag:7hkqA2wLCtOceEWMVFA4Dg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
