apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:bg0undzPiKPQLk90lw4WUroOSfGLhmvhMja6ow9HE8JwFuo/2NSmhI9Ht9hF1+NSSsk4ddqVnu+QIa+ljY9h4lY7V05GREKdrhnlP+fhNZL9JyqqbQj0VUTVHFEAyDuXEVX0sAinrW+pSwWNDKNQ1e1hUzdWDq31/F3KuIXsQ1zKfyHh8+UvwgSPSq/4eexr71bUdh/5pQYoBGLJa3+Y5zMKYqfOiut5GqGdIybkY4Vkw2Om,iv:eN4gjO1RL+jnrOLBHb3S1ONenGK5jdqcouaRb6baGqc=,tag:rwdXkghGnOheUmGA9ErzMQ==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WHE3djh3U09QK05wZmJh
        akY2Nkh4ZTR0YzlsSzFrUWErUk5seHVrdjBrCjN4K2dXbFZtc1NJa2hFYWdIUUFN
        M2hmMlU0OFVkaW96ZHRiVEdhMkxRbU0KLS0tIHY3WjJGM1VGQUh3aXNqOXViOFd3
        bExsVUtZcW0xVWkrV3dhNXpQdkVacEkKisgcKIWJyb4yrdVIggs1tH046AWdD20l
        lljXILbb7EuPPOVu31tDIHBNpP7oHRVwRR2g5AphZrQXNtSTk/2UIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T11:36:10Z"
  mac: ENC[AES256_GCM,data:9XjPhiJ0b1WnbvoXkyty/+oQl1X0LLdZyH5W3snb/p1eJ70vNfuLA9hAwXQM9HbxF9jFKKSNlSxrEBSqK3gdNqLpPMhtJNODw1UyqyjkxV5xbtyakANG8HFxzeYlKdCgx0LpsqXrhU5c7WHgjNyXnqBi8FUJDVlFNxtU1MbV5dY=,iv:0oHUZA6HJMILaHgRrC3RHgHplaBpFqsPCCrP8GLoN2A=,tag:9ltjMkXAUEC+55ruNqwhgQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
