apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:I9gZs75Fh9sW5TqM5D9HsNKDT/vGsVPphkkTg5JGmyGABS2scDpS4uIAZCvchIxWD6zgi6sx+J3yRj5VdOTl0UtAToNQnZPMrCkFfd/34TCBzEp8ftF9m722VMxaQtGh74bNBpZ7j5kPsXiDLsm7KZ1UfODRjlRFmjMov9ziSVYrKmY5UPCzEVKEvBBfUS/bi5BatBnC3ZXiwjXaKkf9E1JhWzcxv5LB7kvnAcNxWGKnbWYfrU8Bmw==,iv:QFVoSJ8UDc7lX283j2PVLPYeNO/OkkOtxxUR7AEFz5E=,tag:rbbrzKV/5V6mW44eS7C53A==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlaHRmUHRLdm13Z3pzaWVO
        eDA2QWxDcktVVmJrOGc2KzhCd3pscFBPbldRCmV5MnA5aUN5aUZCT0o4M2gySXRU
        WDZUaUVjNk1HYWxmVGdNelhBYjFGNlEKLS0tIDV4T2N3SlRBbTlOYU1qbnNXR2Vv
        NUZDajZZWW1DWVpQSzIvaDVuMjlwQ28KueJl7TQV6H+MNOr9EzbhxKn+aoS7qT/7
        fB07f5rH0+hJQEPO35wWrgsoHSxvQ23TIBUQOdFVy7K5HQ+Ger9mdQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T16:30:55Z"
  mac: ENC[AES256_GCM,data:OLwCLEmjdGUXCn7YIx0C9ujhrvyBsP+QVy3Vqo05pJ84mxVovp4+lLYRqsgrQYnlEnPcyzZExB1U0d5WyuluzaE0J3L5gF3ybulKE1KYDCekTSDuGlzb6VT/rTJ1TsKLIOxNmAhJSlpMJKJwkEhugI79eimoutYpgL59YH1198k=,iv:Mw2qxsCwRVaXSmGWOros/3vkh/sX1ZXEDZgYqn+okcc=,tag:5Narri3UGr3Muo5WeYEt6w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
