apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
  hostnames:
    - echo.krapulax.dev
  rules:
    - backendRefs:
        - name: echo
          port: 8080
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjR3VES3o2Y3ozMVFTYVFZ
        NDBlZU5Jb28rTVJNdmhRWWgxeGtUa3g5UkRRCnRBRnNpL0NyRlRucGJGcjh6ZERX
        ZzkzY3ZGbTZHTEowR0ZLRGlldGhBTjgKLS0tIExIb3JMYWExZVdMQTRpRlk0bUJB
        T3g2MHNsNWM1TlRYemVIRTFEcnFGRFkKr6vcc2JBQ3BgeA2xmA04WJzfAw0hLukH
        iXx9M2A0Vr84CXKuet4V1pnyeJnvfQaCoO8V8PLbDUye2rKYPay49Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T10:42:13Z"
  mac: ENC[AES256_GCM,data:On0vcpa3+AU5aAx/u2Bc09tGkMRBtd+i5/lQhWg74PTAHeo0UiV6zdrG1+puRdkFx6ZbBVyGfKLInOOaXcWlNIcWMQantjykZYFUbhNSyfMfMjFaPtyXiTZ/UgzyMeOMGaq9Eh3YQsrD1WS2JIPCIOIrHv5Fd/LeTCX13yPqc2s=,iv:wUdbUIARvqkJStSXBjxK5FDzhOHCy/oDj1rGFh7Uw1M=,tag:KNahq8YCZ8RX0kryFHEOsA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
