apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
  hostnames:
    - echo.krapulax.dev
  rules:
    - backendRefs:
        - name: echo
          port: 8080
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXK1dWdkRVWGp6OW9mc2lw
        cXRpN0JkRG05RzlXR3lWaDlyZUVhYzdHd1JBCkNHWmExQ2hPdk9VeWlvR0tHNlVO
        N2tnQ2hMZnBKWkZCR2ZheVhzTkVqUlEKLS0tICswT2ZxczNCcGJpWXVJNFEvcHVK
        UGkvRjQ0WE5JbjNISGI2RlkyTWZCRUUKHWGaYzcVW+uoe6wWaJxzG4PRiBV+w5xR
        xiZthin1tK8M85yH4YJjRCMBHFZEJG3kfS0TtvGL83JMnbgajXTXpw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T15:42:21Z"
  mac: ENC[AES256_GCM,data:dtqJd1dZk4+UDhjbbcUwY04DNz7yY9JLsLHZdRWXFLXs/kOONiYL2kSF92PRtmhKuibwtEXyZCt81Ckr9RHGzDXrWhEs2FLsw+kE+dB+gQO1XSOvAuMF+yrJAvdDsvbhw4Uu+KTT8Tb7ytGu5m6cOysN4A7pXDvoX2isAobPPRs=,iv:aAMOMjS6FLdRcwWAMyTUYGdl0MbYyvPbFEdIEzFVdqo=,tag:yfE/KAZInRWroLzLOYzMUg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
