fullnameOverride: k8s-gateway
domain: krapulax.dev
ttl: 1
service:
  type: LoadBalancer
  port: 53
  annotations:
    io.cilium/lb-ipam-ips: 10.0.40.153
  externalTrafficPolicy: Cluster
watchedResources:
  - HTTPRoute
  - Service
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdDdHMkRxZXZyV3M3ZGwx
        eU1tMDZnblFSNytFSHNYS0VDRFBocHRFb0FNCkRPWDNIaTZ6TlF2aFVvTG13UFFR
        dVhCVWFFbCtMelFrTFRwaE1zL0Z5NlEKLS0tIFg5REFlN3Z1WmhObHpZZkF5WEFn
        Wk5wOE9RVUNJUWxjNU95LzI2VHFqM2cKq+hKLz+L8+B3M2w1rxv0d5/OUf0GN5P9
        1DZtEjcg9Wl5jfMGEoFMMyNICKqB3k6EmHxIJaZeSNdMA1K3SyEafA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T20:03:32Z"
  mac: ENC[AES256_GCM,data:2SBgxP+t4e0fmBXJSj3JCpM+DnvDrCwknMgLEriVu/Tn32XU442qFr/TMy5n8Nur7kD8bv5r3Yi1506r0GYyEFGmID80DbwRSMDoPEbeeiJ5Fsz+kqYV6dFQXTf8ghtaMfl4oZe5OI4nWuPUThMWuwhqNvYWST2Gv9pPoMoESa4=,iv:gtwewwsKbArt8ny+Wi2R1V2FKtEsW8D5kLAWxXFwzLM=,tag:MFMwAltsQRf4XwbZyDOSVA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
