grafana:
  adminUser: admin
  adminPassword: my-grafana-pa55w0rd
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1b0lremtUZ0M1eTB2Rm9G
        M2tJelZ5c1h0c24zSkpUOWtwaVZVRnlZYjFrCml2NStpZTZoOHFHcG8zM1NPNk16
        amh3ZGdmaXh3NkZ0cStQQjBXa2JGVWMKLS0tIGdHTjRiL2tlZ0lUMmFrNzJQczRP
        enBzcW5FdmNOU0xRc2Jaa09UaEJ2U0EKWWzHSk/ETU27LUocr/CXxh3OiEy6ZjgK
        BYPkHllHRSxYjtwyvYdXHKOad72zRzCMpJzEuV5akpYpx5lMqQhMEg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T19:35:52Z"
  mac: ENC[AES256_GCM,data:MzARfWe9LlVRhlohsM25N3eSPONGMFbbZPglakIgpJclTirECkZcQQYjY1JfA6BUPO+kz3z0K3SlLNa+NbQBYqvmrZAbTMmI6kmqecTJcBUEBlIzdmUJzSDooLjP3a5ilsE/Pr12TVfh02snLUgbTPkuIgYtf8FMK9ug895U3oY=,iv:tYKhzPiIsWvguG93ee+Oy9XXw/wg3qulRNE4pTcIjZ0=,tag:XpvRxe456OfF6AG5s/bvfQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
