grafana:
  adminUser: admin
  adminPassword: my-grafana-pa55w0rd
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoRkg1eHpRT2d5Zjc2MHZU
        MEVpaUtkRnhJaWF0SW1MTGhWckpCWnZYUm5FCjYyMFRhSVZteEZaOTJ1cUtHRGpq
        R0NScERhSlJsNDdtOGJCK2tFRVZ4aGcKLS0tIHBMK2ZpUzQ0OXkxVHFhMVZCc1lF
        WEZ0d1RxbUZES3FUa01uczRwOU4zQXcKkzR0mpq26lIril0ctWejWWGgG3CEU7uv
        JSDzz7Sfv0PhZ46JU3yeOr8GT6U5kFHkR/tDENwxbFVWJgUKAUx8IQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T20:03:32Z"
  mac: ENC[AES256_GCM,data:YCFevyxg/Q08AIqupZu9UBa3M6TU2iMNx5ZgkXXdqCNutNW/fBHG0aBueZafFLYKtJqfKRtErtcafNHpatmq7q+lN0fmL6WecDO1Opa8zUeP0hg8ifQ+38h7i302CH0W7FZ7pNfFrs9pXeBGOsrfw12yhwULTmAV5b/AQ+ZjyyI=,iv:wD+hUSOQ3/O/XFhUFeaeRuWjTYjZoFOWpB/WpbzffpI=,tag:+yHKu9I6dcuHKbOP5PW+6w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
