---
crds:
  enabled: false

defaultRules:
  create: true

alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: cephfs
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 2Gi

grafana:
  enabled: true
  persistence:
    enabled: true
    storageClassName: cephfs
    accessModes:
      - ReadWriteMany
    size: 5Gi
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true
  defaultDashboardsEnabled: true

prometheus:
  enabled: true
  prometheusSpec:
    replicas: 1
    retention: 15d
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1.5Gi
        cpu: "1"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: cephfs
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 20Gi

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true
