apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:EjX3EiDh/mzYRue2T4KrNWz98QCe32luyV3sEHhVBr+C0YnDC873FA==,iv:FHyYoQb1UsbD6rQMJSis8CR67wbX1pnczJOVwLrqNso=,tag:NHpbGz1M70c/mT9j1wFWeQ==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNlBoM2ZZb3MxUkVqcTBn
        dVJYMi8vQisvVHlNNkY3MExOY3ZzTjhBU1VBCkM3R3JQRW9JWnFVb2RtYkFxTlVF
        MkFUMzBOZDdGWk1maldUTzhPSWpYL0UKLS0tIGs0WlZHRjZBRVdWV0FFbTJyL09W
        Y3lvN0VPZE1YYXVtcXVuTXQxUXpOdk0K1LOR+uANOL1u2RFlV1GU+04V2jrUgZ6v
        KgBU5p5Vzi7A84JhXqu39tfsIfHpxdv4pk40g86hPVADLrUmpcVLug==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T20:03:32Z"
  mac: ENC[AES256_GCM,data:++axuScbOUXneXgLVYrJe6EADQ/jnlghu1xspLQzDp5OAzRM3JJmbyDQbU0NvMm3uu33wBZ9scYxos20oZ4yFOxS6ouJM1G/o9b4H7HfebPd89XHXsFTXQgEbqo4RrwD9e0slU62Vvm34vk9uFRPZiDANjwkTmDvfKHHcSF+hNU=,iv:J/4++aGSCN7DnH+2nTf2u9TtknUuDsDGwd3bdrnyFmw=,tag:joQcotE90f7lnvI0u1dFxw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
