apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:tQ1G3ghk5gzblOAv64XjhOVqX5HemCUD6mhueefolac7mqM5FOwlHQ==,iv:lvOxp2RcnFnFFePLvQLVttLgcqk/3g3obQQebTLYgaw=,tag:LT7R4CIu9fAIL1179scuGg==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWGJSektCUUYwanJyNDJo
        c3JqTUZMUC9hQjhBY2pMMS84bWtJeUN2RGxNClcra1dVcDNTbHA3T0NsS2RXbGVQ
        MXF4TENxaEJTSWlWRHoraHBPZ2VMVzAKLS0tIDd4M1pBMnIxYmxMa2NHWGlsUjZI
        OUJCeS9UZGp3VDhNMEk5TVF0aXZTU28K8MWrVGDlaAVV8fGNtTqie57dBO3+rf1M
        yzoVmUrN7J9EHxeFRvnB+G5kttnvj1Qy72bT5gfU/HslwMdeK1h+tw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T19:35:52Z"
  mac: ENC[AES256_GCM,data:ueHcp/wny0THWyHxfDdjWeclQqvY2C1VdxniwTk89fYaYuUCXyGPTC1+GG+8xDqPA2QP/jNT9PmP0sMpGeJyJamCU0uk8pbl/fRFbhrMvP75n3eUhiVlWZBnad5gG62Fq8RuRb4C3UIK1BGtFdp43Vt9dIFGH2IpI4kJvXz/Emk=,iv:OC4xQU7PAR9UG4UQzJEy6ZAA+Al3MOtb7dQZyYRq+3g=,tag:IdEORd+J1nbbqc74BOfvYw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
