apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:qg7naM0P3rB7AxxrjsGsnfFE/Wmwg2RIqSpi7QPT8c8fAMMi+syY6w==,iv:tOp1Q96DDp9pwBkBkTVI/U0pKkgkx14g2cac4TaJ1Vc=,tag:gmo3HkuX6SddjF6Q+anZtw==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NncyNXowVUJMWDEyazAv
        anF2RHI4YXFWWWVkMHBsaU9oeXd4S3U3KzJjCjR6ZDJhVlpPQU5uVENlZjJkTXp4
        Nk9Fclg3WEpsdjBrMjBnTTRQYmVSeGcKLS0tIGJhSUFKTmNlNUdXMlBlSm9kWExz
        djdhOWhtdE5nbUxKck5WOHEvVjJmSG8KNOuLdGH5XHuo+U2zpKBakfWPtfFhgwAA
        8Qt3wLOD45z4/iZdRWEfGS8Z5Q2hWptQNIpkZgLejCENJLggjoW2bw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T15:22:02Z"
  mac: ENC[AES256_GCM,data:/xu+ILA2+752671o6UbeG83db2QhARu39KoucwK25BHcL0L0JWv3jjFIzRpy5LAP1qkHPXtCEuLdfrCk09i7UhqgLPUJ3QCbyyRW9qYglliB376zw0reajD9LskZgNAcjWaDD92AE0bnXi/KmKqYxx5uj4nriy0gcQ42O8CHEAU=,iv:mZ/i3NdH8peKBLBUiQiDfWvmewB5nn/YGvRhP2UiFOg=,tag:M0g2p1fOdd4/8FGg6EZtHA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
