---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-cephfs-pvc
  namespace: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: cephfs
---
apiVersion: v1
kind: Pod
metadata:
  name: test-cephfs-pod
  namespace: storage
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: cephfs-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: cephfs-volume
      persistentVolumeClaim:
        claimName: test-cephfs-pvc
